### ISSUE TITLE
Crashes when dowenloading

### ISSUE THREAD

**Issue by DankMemeGuy** [MalloyDelacroix/DownloaderForReddit#100]
How do I find the logfile?

It crashes at the same user on the list.

**Comment by MalloyDelacroix** [comment]
If you go to the file menu and click "Open Save Location", it will open the folder that contains the log file.

**Comment by DankMemeGuy** [comment]
{"levelname": "INFO", "name": "DownloaderForReddit.DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 89, "message": "Object lists loaded from save file", "asctime": "02/19/2020 07:32:08 PM", "total_users": 92, "total_subreddits": 0, "updated_users": 0, "updated_subreddits": 0, "saved_submissions": 0, "saved_content": 1}
{"levelname": "INFO", "name": "DownloaderForReddit.DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1553, "message": "Save_file successfully loaded into gui", "asctime": "02/19/2020 07:32:08 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.DownloaderForReddit.GUI.DownloaderForRedditSettingsGUI", "filename": "DownloaderForRedditSettingsGUI.py", "module": "DownloaderForRedditSettingsGUI", "funcName": "__init__", "lineno": 46, "message": "Settings dialog opened", "asctime": "02/19/2020 07:32:19 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "run_user_and_subreddit", "lineno": 518, "message": "User and subreddit download initiated", "asctime": "02/19/2020 07:32:27 PM", "user_list_size": 92, "subreddit_list_size": 0, "settings": {"imgur_client_valid": true, "restrict_by_score": false, "score_limit_operator": "GREATER", "score_limit": 3000, "subreddit_sort_method": "HOT", "subreddit_sort_top_method": "DAY", "post_limit": 1000, "restrict_by_date": false, "restrict_by_custom_date": false, "custom_date": 86400, "download_videos": true, "download_images": true, "avoid_duplicates": true, "nsfw_filter": "INCLUDE", "save_subreddits_by": "Subreddit Name", "name_downloads_by": "Image/Album Id", "save_directory": "E:/CONSOLIDATED/Pictures/lol/lol/Reddit/Users/", "max_download_thread_count": 4, "save_undownloaded_content": true}}
{"levelname": "INFO", "name": "DownloaderForReddit.DownloaderForReddit.Core.DownloadRunner", "filename": "DownloadRunner.py", "module": "DownloadRunner", "funcName": "run_extraction", "lineno": 468, "message": "Extraction Runner started", "asctime": "02/19/2020 07:32:28 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.DownloaderForReddit.Core.DownloadRunner", "filename": "DownloadRunner.py", "module": "DownloadRunner", "funcName": "download", "lineno": 535, "message": "Downloader started", "asctime": "02/19/2020 07:32:28 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "start_reddit_extractor_thread", "lineno": 559, "message": "Downloader thread started", "asctime": "02/19/2020 07:32:28 PM"}
{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename": "main.py", "module": "main", "funcName": "log_unhandled_exception", "lineno": 86, "message": "Unhandled exception", "asctime": "02/19/2020 07:32:48 PM", "exc_info": "Traceback (most recent call last):\n  File \"DownloaderForReddit\\GUI\\DownloaderForRedditGUI.py\", line 582, in update_output\nValueError: invalid literal for int() with base 10: 'valid'"}

**Comment by MalloyDelacroix** [comment]
You said that this happens when the downloader gets to a certain user in the list.  By any chance, does this users name start with the word "count"?

**Comment by DankMemeGuy** [comment]
> You said that this happens when the downloader gets to a certain user in the list. By any chance, does this users name start with the word "Count"?

Oh wow didn't notice that. Yes the user's name is "**Count**ry..."
