### ISSUE TITLE
imgur client issue

### ISSUE THREAD

**Issue by MTNdew4** [MalloyDelacroix/DownloaderForReddit#103]
*Issues marked with the **Need Information** label will be closed after 30 days if additional information is not provided*
I put in the client id and client secret, btu it still says "no valid imgur client detected". Help please!

**Comment by MalloyDelacroix** [comment]
I can't say what the issue could be here.  All the application does is save the id and secret you put in and supply it to imgur when extracting content.

I would double check that the information you entered into the dialog is correct and also make sure that your credentials are registered correctly with imgur.  You can see this if you go to your imgur account page and look under applications.  If both of those are good, I would delete the entry under "created apps" and try to make a new one and see if that works.
