### ISSUE TITLE
Video merging critically fails on file not found

### ISSUE THREAD

**Issue by redpoptarts** [MalloyDelacroix/DownloaderForReddit#111]
**Describe the bug**
After a video download, both halves of the file may not have successfully downloaded.
When the VideoMerger tries to merge two files, but only has one, the entire program fails, resulting in a botched download batch.

**Log Output**
`{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename":
{""main.py", "module": "main", "funcName": "log_unhandled_exception",
{""lineno": 86, "message": "Unhandled exception", "asctime": "05/04/2020
{"02:18:40 PM", "exc_info": "Traceback (most recent call last):\n  File
{"\"DownloaderForReddit\\Core\\DownloadRunner.py\", line 250, in
{"downloads_finished\n  File \"DownloaderForReddit\\Utils\\VideoMerger.py\",
{"line 62, in merge_videos\n  File
{"\"DownloaderForReddit\\Utils\\VideoMerger.py\", line 73, in
{"clean_up\nFileNotFoundError: [WinError 2] The system cannot find the file
{"specified: 'D:/Reddit/FILENAME....mp3'"}`

**Environment Information**
 - Operating system:  Windows 10 x64
 - Software version: v2.3.3
 - Are you running a compiled version or from source?:  Compiled

**Comment by MalloyDelacroix** [comment]
This issue has already been fixed.  The most up to date compiled executables can be found [in the actions section](https://github.com/MalloyDelacroix/DownloaderForReddit/actions?query=workflow%3ABuild+branch%3Amaster)
