### ISSUE TITLE
Support for Redgifs.com

### ISSUE THREAD

**Issue by amateurbabes** [MalloyDelacroix/DownloaderForReddit#113]
With Reddit recently introducing Redgifs.com, I was hoping there could be some support for adding it to the list of sites for viable downloading.

**Comment by zacker150** [comment]
Redgifs has been supported since January. Please make sure that you are running the latest build from the GitHub Actions.

**Comment by amateurbabes** [comment]
> Redgifs has been supported since January. Please make sure that you are running the latest build from the GitHub Actions.

I'm gonna be honest, I have no idea what you mean by Github Actions. Even checking that page, I don't really understand. I'm using the latest release which was on December 26, 2019.

**Comment by zacker150** [comment]
Go [here](https://github.com/MalloyDelacroix/DownloaderForReddit/actions?query=workflow%3ABuild+branch%3Amaster). Click on the latest build. Download the build from where it says artifacts.

**Comment by amateurbabes** [comment]
Awesome. Thanks for the help.
