### ISSUE TITLE
Program crashing when saving the settings

### ISSUE THREAD

**Issue by lfvideos** [MalloyDelacroix/DownloaderForReddit#12]
So, i've tried pretty much every version of the software. The program keeps crashing for me when i try to edit my settings. 
Prior 2.1.0 it used to freeze then give me the option to end the process... now after the "save fix"  it only crashes instantly.
I've tried deleting the save file, re-import the save and everything i could think of but nothing seems to work. 

The only thing i can think of is reinstalling the .net framework? would that help?  thanks.

**Comment by MalloyDelacroix** [comment]
The .net framework shouldn't have any effect on the app.  Can you attach your log file?

**Comment by lfvideos** [comment]
Here is what i did.
Deleted everything
Started up the program
Closed the program
Started up the program
Saved (using the menu->save)
Opened the settings and clicked OK (no changes were made)

The program crashed instantly and no messages were shown.

It says something about the date format in the last line of the log... I am from Mexico and we go by "dd/mm/yyyy" format just in case it helps to debug it.

[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/1794917/DownloaderForReddit.log)

**Comment by MalloyDelacroix** [comment]
The problem that you are having is in your time display.  It is formatted to display the date/time as "3/8/2018 04:30 pm".  Somehow your time is being taken as "3/8/2018 04:30 p. m.".  The strange thing is, it should not even be possible for the date/time to display this way.

Can you try opening the settings dialog and checking the date/time in custom date field to the right of the "Restrict downloads by custom date" checkbox.  How is the date displayed in this box?  Is the am/pm indicator displayed as pm or p. m.?  If it is the latter, try changing it to pm.  If you cannot, try setting the date to some other date/time and see if the crashing persists.

If this does not solve the problem I have a few more questions:  
* What operating system are you using?  
* Please open the Imgur credits dialog from the help menu.  How is the date/time displayed at the bottom of the dialog next to "Time user credits reset"?
* How is the date displayed in the restrict by custom date edit in the settings dialog for a user or subreddit?

**Comment by lfvideos** [comment]
OS: Windows 10 Pro x64
Program Version: 2.1.0
Region: Mexico

Test 1: Changed the date from 1/1/1970   (is this unix time?) to today's date and crashing persists.
Test 2: Cant access the imgur credits window since i have not provided an imgur key.
Test 3: The second image should provide the view of the settings dialog for an user

I remember i had an issue like that with a code a very long time ago and i had to convert the local time into "universal time"  wich basically just parsed it differently for the database... not sure if thats the case here but its something that crossed my mind.

thank you for your support so far, hope i can help.

![date 1](https://user-images.githubusercontent.com/37132073/37182482-2e9b398a-22f7-11e8-8f85-12412adba3a7.png)
![date 2](https://user-images.githubusercontent.com/37132073/37182634-db26cbf6-22f7-11e8-98a9-1655e953200b.png)

**Comment by MalloyDelacroix** [comment]
I think I have found a fix for this issue.  It has been implemented in the code base and the next release will incorporate it.  This release is scheduled for either today or over the weekend.  I am not able to reproduce the date being displayed in the same way that it is for you, so I'm not able to test this fix as thoroughly as I would like.  If this does not fix the issue for you, please reopen this issue and I will try again.

Thanks for bringing this to my attention and working with me to get it fixed.
