### ISSUE TITLE
Make the downloaded download comments, and post titles.

### ISSUE THREAD

**Issue by tuskiomi** [MalloyDelacroix/DownloaderForReddit#120]
It's pretty much what it says on the tin, lad. When you made a reddit down loader, I was expecting something like httrack where the page was downloaded, and I think it should be the next step, seing as right now it really only downloads what others post.

**Comment by MalloyDelacroix** [comment]
If I understand you correctly, it seems like you're looking for a web scraper.  This application is not designed to be a web scraper.  It downloads content that is posted to reddit.  It does, however, have settings that will save name the downloaded content file the same as the post title it was extracted from.  Version 3.0 will download comments and text posts also.
