### ISSUE TITLE
Add support for redgifs.com

### ISSUE THREAD

**Issue by mrfreaky411** [MalloyDelacroix/DownloaderForReddit#122]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by mrfreaky411** [comment]
Many reddit gifs have moved from https://redgifs.com/ which is not currently supported for extract

**Comment by MalloyDelacroix** [comment]
Redgifs.com has actually been supported for some time now.  The problem was that the version that supports this was found in the "actions" section instead of the "release" section.  

Pull request  #123 has fixed this, and the latest version can now be found under releases.
