### ISSUE TITLE
How to download previously failed downloads?

### ISSUE THREAD

**Issue by annath918** [MalloyDelacroix/DownloaderForReddit#124]
The latest release supports RedGIFs, but previous versions did not. How can I get the program to download posts that were previously skipped for being unsupported URLs?

**Comment by MalloyDelacroix** [comment]
You should be able to download these posts by going into settings, and unchecking the box next to "Enforce date limits".  As long as "avoid duplicates" is checked, content that has already been downloaded will not be downloaded again.  If you need to set a date limit on the download, you can set a custom date limit in settings as well.
