### ISSUE TITLE
Doesnt start

### ISSUE THREAD

**Issue by Alienmaster** [MalloyDelacroix/DownloaderForReddit#131]
**Describe the bug**
Since V3.0 the downloader doesnt start. Nothing happens and there is no warning/error message

**Environment Information**
 - Windows 10 Pro x64 2004
 - 3.0.0 and 3.1.0
 - compiled

**Comment by lfvideos** [comment]
Check the log, maybe your's has the same issue as mine where the migration is crashing the program

**Comment by Alienmaster** [comment]
Where do i find the log?

**Comment by MalloyDelacroix** [comment]
The log can be found under "C:/Users/UserName/AppData/Roaming/SomeGuySoftware/DownloaderForReddit".

**Comment by Alienmaster** [comment]
`{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename": "main.py", "module": "main", "funcName": "log_unhandled_exception", "lineno": 52, "message": "Unhandled exception", "asctime": "09/03/2020 02:50:20 PM", "exc_info": "Traceback (most recent call last):\n  File \"main.py\", line 101, in <module>\n  File \"main.py\", line 65, in main\n  File \"main.py\", line 58, in check_migration\n  File \"DownloaderForReddit\\database\\migration.py\", line 29, in check_migration\n  File \"DownloaderForReddit\\database\\migration.py\", line 53, in migrate\n  File \"alembic\\command.py\", line 298, in upgrade\n  File \"alembic\\script\\base.py\", line 489, in run_env\n  File \"alembic\\util\\pyfiles.py\", line 98, in load_python_file\n  File \"alembic\\util\\compat.py\", line 184, in load_module_py\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"D:\\DownloaderForReddit\\alembic\\env.py\", line 82, in <module>\n    run_migrations_online()\n  File \"D:\\DownloaderForReddit\\alembic\\env.py\", line 76, in run_migrations_online\n    context.run_migrations()\n  File \"<string>\", line 8, in run_migrations\n  File \"alembic\\runtime\\environment.py\", line 846, in run_migrations\n  File \"alembic\\runtime\\migration.py\", line 509, in run_migrations\n  File \"alembic\\command.py\", line 287, in upgrade\n  File \"alembic\\script\\base.py\", line 364, in _upgrade_revs\n  File \"alembic\\script\\revision.py\", line 777, in _iterate_revisions\n  File \"alembic\\script\\revision.py\", line 321, in get_revisions\n  File \"alembic\\script\\revision.py\", line 501, in _resolve_revision_number\n  File \"alembic\\util\\langhelpers.py\", line 230, in __get__\n  File \"alembic\\script\\revision.py\", line 123, in _revision_map\n  File \"alembic\\script\\base.py\", line 103, in _load_revisions\n  File \"alembic\\script\\base.py\", line 876, in _list_py_dir\nFileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'D:\\\\DownloaderForReddit\\\\alembic\\\\versions'"}`

**Comment by Alienmaster** [comment]
Fixed with 3.1.1
