### ISSUE TITLE
3.1.0 wont migrate my settins (Crash)

### ISSUE THREAD

**Issue by lfvideos** [MalloyDelacroix/DownloaderForReddit#132]
**Describe the bug**
Program doesn't start if there is a previous installation, migration fails.
Works fine on a clean install
Folder alembic\versions  doesn't exist

**Environment Information**
 - Win10 PRO x64
 - 3.1.0 beta
 - Compiled

**To Reproduce** (optional)
1. Open the program

------------------------------------------------------------------------------------------------------------

{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename": "main.py", "module": "main", "funcName": "log_unhandled_exception", "lineno": 52, "message": "Unhandled exception", "asctime": "09/02/2020 11:18:21 AM", "exc_info": "Traceback (most recent call last):\n  File \"main.py\", line 101, in <module>\n  File \"main.py\", line 65, in main\n  File \"main.py\", line 58, in check_migration\n  File \"DownloaderForReddit\\database\\migration.py\", line 29, in check_migration\n  File \"DownloaderForReddit\\database\\migration.py\", line 53, in migrate\n  File \"alembic\\command.py\", line 298, in upgrade\n  File \"alembic\\script\\base.py\", line 489, in run_env\n  File \"alembic\\util\\pyfiles.py\", line 98, in load_python_file\n  File \"alembic\\util\\compat.py\", line 184, in load_module_py\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"C:\\Users\\VIDS\\Downloads\\DownloaderForReddit\\alembic\\env.py\", line 82, in <module>\n    run_migrations_online()\n  File \"C:\\Users\\VIDS\\Downloads\\DownloaderForReddit\\alembic\\env.py\", line 76, in run_migrations_online\n    context.run_migrations()\n  File \"<string>\", line 8, in run_migrations\n  File \"alembic\\runtime\\environment.py\", line 846, in run_migrations\n  File \"alembic\\runtime\\migration.py\", line 509, in run_migrations\n  File \"alembic\\command.py\", line 287, in upgrade\n  File \"alembic\\script\\base.py\", line 364, in _upgrade_revs\n  File \"alembic\\script\\revision.py\", line 777, in _iterate_revisions\n  File \"alembic\\script\\revision.py\", line 321, in get_revisions\n  File \"alembic\\script\\revision.py\", line 501, in _resolve_revision_number\n  File \"alembic\\util\\langhelpers.py\", line 230, in __get__\n  File \"alembic\\script\\revision.py\", line 123, in _revision_map\n  File \"alembic\\script\\base.py\", line 103, in _load_revisions\n  File \"alembic\\script\\base.py\", line 876, in _list_py_dir\nFileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'C:\\\\Users\\\\VIDS\\\\Downloads\\\\DownloaderForReddit\\\\alembic\\\\versions'"}

**Comment by MalloyDelacroix** [comment]
Fixed by 534832ca9369056836d67aee36067404c398ac0a
