### ISSUE TITLE
Clicking "Imgur Credits" Crashes the Program

### ISSUE THREAD

**Issue by amateurbabes** [MalloyDelacroix/DownloaderForReddit#133]
It's as the title says. Clicking Imgur Credits crashes the program. It's the latest beta version.

**Comment by MalloyDelacroix** [comment]
Have you entered valid imgur credentials in the imgur section of the settings menu?

**Comment by amateurbabes** [comment]
I did not. I feel like that's a bit of an oversight, especially when it crashes if you never checked settings. Maybe just add a pop up saying to check your settings under Imgur would help.

**Comment by MalloyDelacroix** [comment]
I agree, it is an oversight.  Without credentials is the only way I could replicate the error, so I just wanted to make sure this was the cause.

**Comment by amateurbabes** [comment]
Then all is well.

**Comment by MalloyDelacroix** [comment]
Fixed with #139.
