### ISSUE TITLE
Audio Fails to Download

### ISSUE THREAD

**Issue by samkarpenter** [MalloyDelacroix/DownloaderForReddit#135]
Hello. Love the app. For some reason, the audio from reddit video fails to download. WHen I check the "failed download" section, the audio file shows up in the report. 

I have ffmpeg installed properly.

Is this a bug that everyone has or it's just me? Am I doing something wrong?

Thank you!

**Comment by MalloyDelacroix** [comment]
Can you attach your log file?

**Comment by samkarpenter** [comment]
Certainly. Here it is. Thank you.

[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5185015/DownloaderForReddit.log)

**Comment by MalloyDelacroix** [comment]
Fixed with #139.

**Comment by samkarpenter** [comment]
Thank you very much for your time!
