### ISSUE TITLE
Unable to download YouTube videos & reddit comments

### ISSUE THREAD

**Issue by etec-masterofsynapse** [MalloyDelacroix/DownloaderForReddit#136]
I am using your project to download some subreddits.
However from the start I am having massive issues with not being able to download YouTube videos. It always says Unknown error occurred or Unsupported domain. However in the settings I can see that YouTube itself is supported. And I saw that you are (maybe) using youtube-dl, it is available through my PATH, however I dont see it being used.

Also for one specific subreddit it is unable to download many comments with the error Unknown error occurred or Unsupported domain. Maybe they are deleted and thats why.

**Comment by MalloyDelacroix** [comment]
Can you attach your log file?

**Comment by etec-masterofsynapse** [comment]
@MalloyDelacroix Could you please instruct me how I get the log file you need? I only saw the errors during the running process in the debug section of the window.

**Comment by MalloyDelacroix** [comment]
The easiest way to get there is to run the application, then click "Open Data Directory" from the file menu.

**Comment by etec-masterofsynapse** [comment]
Attached one of the logs.
[DownloaderForReddit1.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5188051/DownloaderForReddit1.log)

**Comment by MalloyDelacroix** [comment]
I believe I have resolved the comment issue.  I cannot replicate the failed youtube extraction.  Are you running from source or compiled executable?

**Comment by etec-masterofsynapse** [comment]
I am running the newest compiled executable (at the time), version 3.1.1-beta.
There is a 3.2.0-beta available now, should I update to that?
