### ISSUE TITLE
Can't modify the program folder after opening and clossing it

### ISSUE THREAD

**Issue by lfvideos** [MalloyDelacroix/DownloaderForReddit#142]
**Describe the bug**
After running the program and closing it i can´t seem to be able to rename or modify it.
For example when i open it and there is a new update, i cant delete the old version and get the new one in the same folder because something "is still running"  i can't seem to be able to find it in the task manager but i have to restart my pc in order to be able to delete/rename the folder 

**Environment Information**
 - Win10 Pro x64
 - All versions since 3.0.0
 - Compiled

**To Reproduce** (optional)
1. Open the exe
2. close the exe
3. try to rename /delete the folder

**Comment by MalloyDelacroix** [comment]
This is not an error I have run into before.  I have some questions:

1. Are you running a download before closing the app?  If so, is the download complete?
2. Do you run it in perpetual mode, or have a download schedule set?
3. Does it only happen after alerting you of a new version?

Also, can you please attach your log file?

**Comment by lfvideos** [comment]
> 
> 
> This is not an error I have run into before. I have some questions:
> 
>     1. Are you running a download before closing the app?  If so, is the download complete?
> 
>     2. Do you run it in perpetual mode, or have a download schedule set?
> 
>     3. Does it only happen after alerting you of a new version?
> 
> 
> Also, can you please attach your log file?

1.- Sometimes yes but normally no. 
2.- Negative, all my downloads are manual
3.- Apparently yes, i've been trying to reproduce it but so far it only happens when im installing a new version into the same folder (after closing the app)
