### ISSUE TITLE
Infinite loop is breaking the software

### ISSUE THREAD

**Issue by mananas77** [MalloyDelacroix/DownloaderForReddit#155]
**Describe the bug**

1. The software always become stuck in a loop, and never gets completed when i try to download all the posts of a subreddit. 

2. It's seems that the software encounter some sort of download error that it can't recover from and then get stuck in a loop. I've tried to wait more then 18 hours without any progress at all. 

3. At this point i'm unable to do any action related to "Stop Download" And "Terminate Download".

4. When i finaly exit the software it's still running in the background and i have to Terminate in task manager.

5. If i start again and try to download or "Run unfinished". It gets finished in 3 sec without any new files downloaded. And at this point i'm locked from downloading any remaining posts and have to delete the database to get a new chance.

6. It also seems that the url extraction part works while i'm running my download and something gets dumped into the database. But the database don't seem to recognice if the url has been downloaded or not and tells the software "if url is in the database, don't download".

**Environment Information**
- Windows 10 Home
- Every Software version from v3.0.0-beta up-to the current build.
- Tried every compiled version.

**Steps to reproduce my latest encounter of the behavior:**
1. Start with a fresh build of the latest software version (Remember to remove your old config and db)
2. Go to settings and add Imgur credentials (or else you get more errors)
2. Add a new subreddit like "aww" or try with a couple that have many images and videos.

3. Use these settings on the subreddit and everything else default.

![Settings](https://user-images.githubusercontent.com/44532050/95493977-7efda680-099d-11eb-893f-d583ee7b32a3.jpg)

4. Start the download and let the bug begin.

![Bug](https://user-images.githubusercontent.com/44532050/95493880-655c5f00-099d-11eb-94fb-181e08f2ec8b.jpg)

5. The extraction of all urls will get completed but not the downloading part. (Terminate software in task manager when you get bored and try again with same result)

**For all but the most trivial of issues, please attach the latest log file.**

[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5350446/DownloaderForReddit.log)

**Comment by MalloyDelacroix** [comment]
I believe I'm narrowing in on this issue.  If you wouldn't mind to run a follow up test for me, I can verify that I'm on the right path.  Can you run this again exactly the way you described, but go into settings under "core" and change the multi-part download threshold to 10 GB.  Let me know if it runs correctly after doing this.

**Comment by mananas77** [comment]
Yes you are right, with "multi-part download threshold 10 GB" it did go all the way to completion.
I did two tests in the same manner with the new threshold.

**First test:** 
![First run](https://user-images.githubusercontent.com/44532050/95613994-14fd0400-0a66-11eb-90ca-94c3467bba61.jpg)

1. Completed but about 100-150 console output errors in relation to "Url:https://v.redd.it/**********"

**ERROR: Failed to extract due to: Unsupported domain
ERROR: Failed to extract due to: Unknown error occurred
ERROR: Failed to extract due to: Unsuccessful response from server**

2. Also got spammed with some hundred cmd.exe windows related to FFmpeg

**Log:**
[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5356599/DownloaderForReddit.log)

**Second test**
![test2](https://user-images.githubusercontent.com/44532050/95615100-ef70fa00-0a67-11eb-8e3e-40b1f92c2f63.jpg)

1.Here i wanted to end the download midway but was not allowed to stop or terminate download. It just kept going.

2. I did shutdown the software and started up again anew

3. Tried to run unfinished downloads again to get the remaining 500 posts but only got this output

![test2b](https://user-images.githubusercontent.com/44532050/95616046-7bcfec80-0a69-11eb-858a-777d10bcb7fc.jpg)

**Log:**
[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5356723/DownloaderForReddit.log)

**Comment by mananas77** [comment]
**I just did a Third longer test with more subreddits that was a real pain in the butt**

1. After about 22 minutes the progress bar went missing
![progressbar](https://user-images.githubusercontent.com/44532050/95625967-b3469500-0a79-11eb-8cd9-01346ca4be57.jpg)

2. When FFmpeg started to do its thing the computer was unusable with all the popups. There was certainly more than a thousand and every couple av minutes i had to make manual decitions like this one:

![ffmpeg](https://user-images.githubusercontent.com/44532050/95626616-e9d0df80-0a7a-11eb-8145-8254a7e40856.jpg)

3. With all manual decisions that had to be done to continue downloading the progress was a lot slower and tedious but it did complete in the end.

![finished](https://user-images.githubusercontent.com/44532050/95627023-bcd0fc80-0a7b-11eb-98cd-4e7daeb81407.png)


[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5357276/DownloaderForReddit.log)
[DownloaderForReddit2.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5357282/DownloaderForReddit2.log)
