### ISSUE TITLE
A couple more bugs/issues

### ISSUE THREAD

**Issue by ghost** [MalloyDelacroix/DownloaderForReddit#16]
* It's possible to open more than one instance of the program. (make this an option?)
* Clicking [download] places a * in the titlebar as if settings need to be saved again?
* Lists menu - "Rmove Subreddit List"
* Some child windows appear in random locations (annoying on multimonitor). maybe centre to parent?

**Comment by MalloyDelacroix** [comment]
* It is possible to open more than one instance.  All instances will read from and save to the same save file, which will cause problems when the save file is saved.  Changes made to the file from the first save will be overwritten on subsequent saves from other instances.  There is a major change planned for version 3.0 that I believe will allow multiple instances to operate better though.

* Settings are not the only thing being saved when save is clicked.  Most of what is saved is from the user and subreddit objects in the lists.  These objects hold urls that have already been downloaded, a current "last extracted post date", and various lists of saved items and settings that are updated automatically by the program when the downloader is ran.  To keep these items up to date you must save after the running the downloader.

* This typo (and the other that you reported) have been corrected in the code and will show up in the next release.

* I will try to fix this issue for the next release.

**Comment by MalloyDelacroix** [comment]
Tertiary windows should all now open in the center of the main window.
