### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by mananas77** [MalloyDelacroix/DownloaderForReddit#161]
1. I got stuck in an endless loop when the downloader tried to modify a .mp4 file that didn't exist. The video should have been downloaded because it really do exist: https://v.redd.it/9nmkuzw33us51

2. The LOG don't seem to give an error when failing to download (video) and only give errors about (audio).

3. Downloading silent videos that doesn't have audio at all result in an Audio related error like this one: 

{"levelname": "ERROR", "name": "DownloaderForReddit.core.downloader", "filename": "downloader.py", "module": "downloader", "funcName": "log_errors", "lineno": 185, "message": "Failed Download: Unsuccessful response from server", "asctime": "10/13/2020 09:20:10 PM", "exc_info": "NoneType: None", "url": "https://v.redd.it/9nmkuzw33us51/DASH_audio.mp4?source=fallback", "title": "This head game is insane!(audio)", "submission_id": "jaa93q", "user": "USER: History0470", "subreddit": "SUBREDDIT: nextfuckinglevel", "save_path": "D:/Reddit/test/History0470/nextfuckinglevel/None.mp3", "status_code": 403}

**Environment Information**
 - Windows 10 Home
 - Software version v3.2.2-beta
 - Compiled version

LOG:
[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5374029/DownloaderForReddit.log)

**Comment by MalloyDelacroix** [comment]
I don't know what was causing the endless loop that you described, but the underlying problem with reddit videos has been fixed.  So I will close this issue for now.
