### ISSUE TITLE
v3.3.1-beta  DownloaderForReddit.exe flagged as Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by Thr3d** [MalloyDelacroix/DownloaderForReddit#163]
**Describe the bug**
v3.3.1-beta DownloaderForReddit.exe is flagged by Windows Defender as [Trojan:Win32/Wacatac.B!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.B!ml&threatid=2147735505)

**Environment Information**
    Windows 10
    Software version v3.3.1-beta
    Compiled version

**Comment by MalloyDelacroix** [comment]
It looks like this is somewhat of a known issue when compiling a program with Pyinstaller.  Apparently, Defender sometimes flags programs compiled with Pyinstaller as malicious.  This is not something I can do anything about other than assure you that there is nothing malicious about this application.
