### ISSUE TITLE
Issues with WEBM-Files

### ISSUE THREAD

**Issue by T-prog3** [MalloyDelacroix/DownloaderForReddit#171]
All .WEBM files downloaded by the software is just 0 bytes size.

**Comment by DimsumDynamite** [comment]
I'm having the same issue. Also any reason why they are WEBM files when the previous version happily download MP4? I much prefer MP4.

**Comment by MalloyDelacroix** [comment]
Can you attach your log file?

@DimsumDynamite The format of the downloaded file is the same as the hosted file format.  The only difference is with Imgur gifs, which are sometimes hosted as .gifv files but can be downloaded as .mp4 files.  But this is available through Imgurs api.  There is no other conversion that takes place.

**Comment by T-prog3** [comment]
There is no log entries on this error. All i can say is that the software downloads .WEBM files but all become 0 byes and are corrupted.

**Comment by MalloyDelacroix** [comment]
I can't reproduce this error.  Without the log file, there is nothing I can do.  There is more information in the log file that may be relevant even though it doesn't appear so.
