### ISSUE TITLE
Missing Image/Album ID for naming downloaded files from older version

### ISSUE THREAD

**Issue by kmanlives** [MalloyDelacroix/DownloaderForReddit#173]

**Comment by MalloyDelacroix** [comment]
This has been added to the token naming system.  It is available in download settings or individual user/subreddit settings as naming tokens in the Download Naming and Save Path Structure sections as "Media Id".  

Note, however, that these media ids are not available from all container sites and some sites may return unexpected ids (gfycat for example does not return standard alphanumerical ids but rather unique word combinations).  If a media id is not supplied by the container site, this token will fallback on the submission id.
