### ISSUE TITLE
Software fail to extract content if there is a NSFW confirmation

### ISSUE THREAD

**Issue by T-prog3** [MalloyDelacroix/DownloaderForReddit#174]
The software fails to extract content from both reddit and imgur if there is a NSFW confirmation overlay before the content shows. This happens with this type of url https://www.reddit.com/****** and https://imgur.com/********. Seems to be other issues with this kind of url also that is not NSFW related.

**Environment Information**
 - Windows 10 Pro
 - Software version v3.3.2-beta
 - Compiled version

**Log file.**
[DownloaderForReddit.txt](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5543435/DownloaderForReddit.txt)

**Comment by MalloyDelacroix** [comment]
This issue turned out not to be related to NSFW posts but rather with crossposted galleries/albums.
