### ISSUE TITLE
How to support the project?

### ISSUE THREAD

**Issue by wuuei** [MalloyDelacroix/DownloaderForReddit#186]
Hello,

I realize that might be the wrong place to ask, but I didn't find any other place.
Is there a way to support the development?
Specifically monetarily, as I don't know how to contribute with code :)
A Patreon or PayPal account, for example.

**Comment by MalloyDelacroix** [comment]
It means a lot that you enjoy the app enough to want to donate to it.  I sincerely appreciate this.

I've added a paypal donate button to the readme page.

Thanks again!
