### ISSUE TITLE
Issue with deleted users

### ISSUE THREAD

**Issue by T-prog3** [MalloyDelacroix/DownloaderForReddit#189]
When a user is either suspended or deleted you have this window who ask if you want to remove the user from your list (YES / NO). When i press "No" on this alert it will crash the software the second or third time a similar window appears.

**Environment Information**
 - Windows 10 Pro
 - Software version v3.6.0-beta
 - Compiled version

**Comment by MalloyDelacroix** [comment]
Can you attach your log?

**Comment by T-prog3** [comment]
All that i do is having a list with three deleted users from a larger list.
and let the download run until finish. When it's done i press either yes or no on the alert and then it always crash on the second users alert.

Here is the log.
[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5758409/DownloaderForReddit.log)
