### ISSUE TITLE
Can't save settings

### ISSUE THREAD

**Issue by onesolo** [MalloyDelacroix/DownloaderForReddit#19]
Using the last version but when I try to save settings, the program exists completely and doesn't save any settings!!!
Also tried the previous version and the same happens.
Is there a way to edit the settings, like a config file?? If yes, where is located?? Couldn't find it...

**Comment by MalloyDelacroix** [comment]
Can you attach your log file?

**Comment by onesolo** [comment]
And where are those logs?? I couldn't found them...

**Comment by MalloyDelacroix** [comment]
The log file is in the user data folder under "SomeGuySoftware/DownloaderForReddit".  If you click on File > Open Save Location it should open the correct folder.

**Comment by marciocesarcorrea** [comment]
[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/2029379/DownloaderForReddit.log)

{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 83, "message": "Object lists loaded from save file", "asctime": "05/23/2018 12:16:32 AM", "total_users": 1, "total_subreddits": 1, "updated_users": 0, "updated_subreddits": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1325, "message": "Save_file successfully loaded into gui", "asctime": "05/23/2018 12:16:32 AM"}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditSettingsGUI", "filename": "DownloaderForRedditSettingsGUI.py", "module": "DownloaderForRedditSettingsGUI", "funcName": "__init__", "lineno": 47, "message": "Settings dialog opened", "asctime": "05/23/2018 12:16:34 AM"}
{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename": "main.py", "module": "main", "funcName": "log_unhandled_exception", "lineno": 86, "message": "Unhandled exception", "asctime": "05/23/2018 12:17:15 AM", "exc_info": "Traceback (most recent call last):\n  File \"DownloaderForReddit\\Core\\SystemUtil.py\", line 117, in get_epoch\n  File \"DownloaderForReddit\\Core\\SystemUtil.py\", line 127, in get_time_int\n  File \"_strptime.py\", line 559, in _strptime_time\n  File \"_strptime.py\", line 362, in _strptime\nValueError: time data '1/11/2000 10:00 ' does not match format '%m/%d/%Y %I:%M %p'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"DownloaderForReddit\\GUI\\DownloaderForRedditSettingsGUI.py\", line 263, in accept\n  File \"DownloaderForReddit\\GUI\\DownloaderForRedditSettingsGUI.py\", line 286, in save_settings\n  File \"DownloaderForReddit\\Core\\SystemUtil.py\", line 123, in get_epoch\n  File \"DownloaderForReddit\\Core\\SystemUtil.py\", line 127, in get_time_int\n  File \"_strptime.py\", line 559, in _strptime_time\n  File \"_strptime.py\", line 362, in _strptime\nValueError: time data '1/11/2000 10:00 ' does not match format '%m/%d/%Y %I:%M %p'"}
