### ISSUE TITLE
Right clicking on empty Subreddits field crashes (Windows 10)

### ISSUE THREAD

**Issue by Zhuinden** [MalloyDelacroix/DownloaderForReddit#196]
**Describe the bug**

**Environment Information**
 - Operating system Windows 10
 - Software version [e.g. 2.3.0]: 3.7.0-beta
 - Are you running a compiled version or from source? Compiled

**To Reproduce** (optional)

**For all but the most trivial of issues, please attach the latest log file.**

------------------------------------------------------------------------------------------------------------

**Note:** All issues marked with the **Information Needed** label will be closed after 30 days if no information is provided.

![image](https://user-images.githubusercontent.com/11718392/105633997-10652b80-5e5c-11eb-824b-14a0dc49e83e.png)

Right click crashes the app.

**Comment by MalloyDelacroix** [comment]
Fixed by #195
