### ISSUE TITLE
REQ: Import usernames/subreddits from a text file?

### ISSUE THREAD

**Issue by EC-O-DE** [MalloyDelacroix/DownloaderForReddit#2]
Import usernames/subreddits from a text file?

A list that I'm following is on at text file, I'd like to import that to the app...
Manually wayyy slow by adding one at a time :/

**Comment by MalloyDelacroix** [comment]
This feature has been added to the master branch.  To access it, right click on the add user/subreddit buttons and select "Add Subreddits From Text File."  Select the text file where the names are stored and it will import them.  Each name must be on a new line or must be separated by commas.

This feature will not be officially documented until the next release.

**Comment by EC-O-DE** [comment]
Seems that this isn't working on the latest version..

**Comment by MalloyDelacroix** [comment]
This feature has been revised in the new version.  It is no longer available by right clicking the add user/subreddit button.  To access it: click the add user/subreddit button and then right click anywhere in the dialog (except the text field at the moment, but this will be fixed going forward) and select "Import From File".

Sorry for the confusion.  This was mentioned in the latest release, but was not made entirely clear and the user manual has not been updated yet.

**Comment by EC-O-DE** [comment]
thanks for keeping the app up and running!
