### ISSUE TITLE
No GIF Downloads from RedGifs

### ISSUE THREAD

**Issue by areyourmymummy** [MalloyDelacroix/DownloaderForReddit#212]
So I am trying to download a users profile and any gifs/videos they have posted. It seems like any that are hosted in RedGifs are being skipped. This may just be an issue on my end, but I’m not sure. Any help would be great. Thanks

**Comment by zacker150** [comment]
Did you download the latest update?

**Comment by areyourmymummy** [comment]
🤔 i think I have the latest version. I downloaded it straight from the build section. Do I need to update within the app itself?

**Comment by areyourmymummy** [comment]
I just checked and I have the latest version

**Comment by MalloyDelacroix** [comment]
I cannot reproduce this behavior.  Can you attach your log file?
