### ISSUE TITLE
How to download ALL images and videos from day 1? Only getting some images and very very few videos

### ISSUE THREAD

**Issue by dareksartre** [MalloyDelacroix/DownloaderForReddit#214]
How to download ALL images and videos from day 1? Only getting some images and very very few videos...

Win 10 x64
Latest DFR
Latest patch

![Untitled](https://user-images.githubusercontent.com/83517555/118226915-53d9b900-b490-11eb-950f-5f96c97e9f0b.png)

**Comment by dareksartre** [comment]
^that is for default user list (also same for master user list)

**Comment by MalloyDelacroix** [comment]
The reddit API limits the number of posts that you can pull to 1,000.  Depending on how active the sub/user is, you will not be able to get all of the posts with this limitation.

If you are getting significantly fewer than 1,000 posts from a user/subreddit, there may be an issue involved, but I would have to see your log file to diagnose.

**Comment by dareksartre** [comment]
some images come corrupted and many video files downloads as .part files.
i deleted all all corrupted images and .part video files - now though I'm not sure if I should re-download ALL again ( ? )

So what do you recommend as post limit? 500?

I'm downloading users not subreddits. It's usually around 20-100 files per user (I guess).

**Comment by MalloyDelacroix** [comment]
You should be able to download at the 1,000 post limit without problems.  If you were getting close to 1,000 files per download, I would think it is the API limit that is keeping you from getting all of the files from when the user started posting.  But this does not appear to be the case.  Corrupted files suggest another problem.  

If you could attach your log file, I may be able to diagnose the problem.  (It's located at "C:/Users/<username>/AppData/Roaming/SomeGuySoftware/DownloaderForReddit/"

**Comment by dareksartre** [comment]
could I send the log to email, pm, etc?

**Comment by MalloyDelacroix** [comment]
Yes, you can email the log file to downloaderforreddit@gmail.com.
