### ISSUE TITLE
CORS? issues on Reddit (old and new)

### ISSUE THREAD

**Issue by dareksartre** [MalloyDelacroix/DownloaderForReddit#215]
Image/video/thumbnail functionality on old and new Reddit is much restored with CORS
https://chrome.google.com/webstore/detail/cross-domain-cors/mjhpgnbimicffchbodmgfnemoghjakai

Install it, remove default rule, add your rules, save and enable
![Untitled](https://user-images.githubusercontent.com/83517555/118230075-bb463780-b495-11eb-9324-d20ce9266600.png)

As it's Reddit API could it be that similar cross-site issues are at DFR tool?

**Comment by MalloyDelacroix** [comment]
CORS rules do not apply to DFR since it is a desktop app.
