### ISSUE TITLE
can't download redgifs.com

### ISSUE THREAD

**Issue by heppphepp** [MalloyDelacroix/DownloaderForReddit#216]
can't download redgifs.com 

plz help

and Not included supported_video_sites

**Comment by MalloyDelacroix** [comment]
This is a duplicate of #212.

Can you attach your log file?  If you don't want to attach it, you can send it privately to downloaderforreddit@gmail.com.

**Comment by heppphepp** [comment]
[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/6520585/DownloaderForReddit.log)
