### ISSUE TITLE
Scheduling a download

### ISSUE THREAD

**Issue by JimbiJones** [MalloyDelacroix/DownloaderForReddit#22]
More of an enhancement idea than an issue.  

Is there a way or plans to schedule a download at regularly set intervals?  I find that some users are deleting posts after they have been up for less than a day and I would like to capture it if I am not at the computer.

**Comment by MalloyDelacroix** [comment]
There was a plan for a continuous download option for future versions.  This would also make a good addition though.  I will look into including it in the future. Thanks for the suggestion.

**Comment by Chrisnetika** [comment]
I second this idea!

**Comment by Merlin7x** [comment]
I third(?) this idea! Using a tool to make my mouse click on a timer at the moment, would love it if it was a feature instead. Either way, awesome tool, thank you very much for sharing!

**Comment by ma-tt** [comment]
Being able to run every X days/X hours would be excellent. Really the one key feature that is missing.

**Comment by DankMemeGuy** [comment]
> There was a plan for a continuous download option for future versions. This would also make a good addition though. I will look into including it in the future. Thanks for the suggestion.

Were you planning on integrating this into the next version? Or would you know of a 'bootleg' way i could go about automating the current version?

**Comment by MalloyDelacroix** [comment]
This will be a part of version 3.  A user above mentions using some tool to make his mouse click the download button on a timer.  I don't know how well that works, but it's about the only way I know of to get this functionality currently.
