### ISSUE TITLE
Version 3.9.0-beta won't launch

### ISSUE THREAD

**Issue by Fergo** [MalloyDelacroix/DownloaderForReddit#220]
**Describe the bug**
When double clicking the executable, nothing happens. No process is created in task manager either.

**Environment Information**
 - Operating system: _Windows 10_
 - Software version: _3.9.0-beta_
 - Are you running a compiled version or from source? _Compiled, from releases page_

**To Reproduce** (optional)
1. Double click the executable
2. Wait for program to launch, but nothing happens

**For all but the most trivial of issues, please attach the latest log file.**

No log file is created either in the ```AppData\Roaming\SomeGuySoftware\DownloaderForReddit``` folder.

------------------------------------------------------------------------------------------------------------

**Note:** All issues marked with the **Information Needed** label will be closed after 30 days if no information is provided.

**Comment by MalloyDelacroix** [comment]
Could this be an issue with an anti-virus product of some kind?  If there is no log file created, I don't think it could be an issue happening from inside the app.  The first thing that it does is roll the except hook into the log file.  So even if an uncaught error happens at the very start, it would be logged.

Is a database or configuration file created?

**Comment by Fergo** [comment]
Thanks for replying. I'm not running 3rd party AV software (only the regular Windows Defender).
Running from cmd also exited immediately with no output.
Yes, the database file is there, but it was created by a previous version of the software (3.8 I think)

**Comment by MalloyDelacroix** [comment]
There are new releases since this, and no new comments.  I'm assuming this issue is resolved.
