### ISSUE TITLE
gfycat : Failed to retrieve json data from link

### ISSUE THREAD

**Issue by Hastte** [MalloyDelacroix/DownloaderForReddit#224]
Have the latest version but still this problem occurs
Errors for all gifs
Main error :  ```status_code: 404 and AttributeError: 'NoneType' object has no attribute 'name'```

**Comment by MalloyDelacroix** [comment]
Can you post that whole error message?  I can't tell enough about it from this.  If you don't want to post it publicly, you can email the log file to downloaderforreddit@gmail.com where only I'll see it.
