### ISSUE TITLE
"Hide Window" eventually leads the application to crash with Scheduled Downloads of Subreddit List

### ISSUE THREAD

**Issue by iratekalypso** [MalloyDelacroix/DownloaderForReddit#231]
**Describe the bug**
I have an hourly scheduled download of about 8 large-ish subreddits. To save taskbar space, I opted to "Hide Window":
![image](https://user-images.githubusercontent.com/64004674/127926421-ffe43655-8c1a-4e7b-9d4f-e9e86ee6cd64.png)
This functions fine for a few hours, but eventually leads to a crash of the application everytime I leave it running for any decent amount of time.

If I leave it on "Show Window" and just minimize it to the taskbar, I do not run into this issue.

**Environment Information**
 - Windows 10 Home 21H1 19043.1110 "Windows Feature Experience Pack 120.2212.3530.0"
 - Downloader For Reddit v3.10.2-beta
 - Compiled version

**To Reproduce** (optional)
1. Load up 8 subreddits of decent size to a list
2. Create an hourly scheduled download of this list
3. Hide Window
4. Wait for it to crash
4.5 I notice "Run Time" just keeps increasing aswell. Doesn't reset with new downloads
5. Wait for it to crash.
6. Profit???

**Comment by MalloyDelacroix** [comment]
Can you attach your latest log file?
