### ISSUE TITLE
Downloading Individual Reddit Posts

### ISSUE THREAD

**Issue by loggerheads-on-binary** [MalloyDelacroix/DownloaderForReddit#240]
**Is your feature request related to a problem? Please describe.**
This is a request for an added feature, besides users and subreddits, to be able to download individual posts. As of now there's no way to download an individual [post like this](https://www.reddit.com/r/mildlyinfuriating/comments/q1n65t/in_response_to_all_the_people_asking_me_to/) with multiple media files in it.  

**Describe the solution you'd like**
A GUI section or any other way to download individual posts

**Additional context**
For example, as of now if I have to download a post [say this one](https://www.reddit.com/r/mildlyinfuriating/comments/q1n65t/in_response_to_all_the_people_asking_me_to/) I usually check the username of the poster, add it to the users, download the latest post and then remove the user from the user list. This can be cumbersome and works only for new submissions. Age-old posts may not be downloadable. 

Alternatively, would also appreciate without the GUI, even just a function would do which I can import from my script. However, as of now, there seems no concrete way to be able to do this without instantiating a GUI object. 

(Apologies for any error. English is not my first language)

**Comment by crccheck** [comment]
I've been using Gallery-dl for ad-hoc reddit downloads https://github.com/mikf/gallery-dl

**Comment by loggerheads-on-binary** [comment]
Sounds perfect for my use case. Thanks @crccheck
