### ISSUE TITLE
Stuck after a while

### ISSUE THREAD

**Issue by thany** [MalloyDelacroix/DownloaderForReddit#244]
**Describe the bug**
The program gets stuck "downloading" (not really) after a while. I don't know what triggers it. I onlyknow that it gets into some kind of intermediate state, where it's not possible to either resume downloading, or stop downloading. It's in a kind of limbo.

Sure I can kill the process, but that will also kill any progress, causing it to happily download already-downloaded files, appending `(1)` to the filename to force uniqueness (which is totally bonkers on its own, but that's a different issue from this one).

So it's stuck. And here's how:

No CPU usage
No GPU usage
Very occasional disk I/O usage
Almost no network I/O usage

The most notable thing is that it keeps 2 connections open:
```
DownloaderForReddit.exe (1844), <redacted hostname>, 53422, 199.232.149.140, 443, TCP, Established, 
DownloaderForReddit.exe (1844), <redacted hostname>, 53635, 176.56.179.186, 80, TCP, Established, 
```
And ONLY these two. If I kill these, the download process completes with an error `Failed to save content` without mentioning a reason.

**Environment Information**
 - Windows 10
 - Software version 2.3.4
 - Are you running a compiled version or from source? -> Yes

**To Reproduce** (optional)
1. Download
2. Download some more until the above happens
3. Pray to a deity of choice that your debug tools are running, because I can't tell you for the life of me how to reproduce this reliably.

**For all but the most trivial of issues, please attach the latest log file.**

Sure, but I think this line is what you're going to need:

```json
{
    "levelname": "ERROR",
    "name": "DownloaderForReddit.DownloaderForReddit.Core.Content",
    "filename": "Content.py",
    "module": "Content",
    "funcName": "handle_exception",
    "lineno": 182,
    "message": "Failed to save content: Exception while saving file",
    "asctime": "10/18/2021 08:07:28 PM",
    "exc_info": "Traceback (most recent call last):\n  File \"DownloaderForReddit\\Core\\Content.py\", line 108, in run\n  File \"site-packages\\requests\\api.py\", line 75, in get\n  File \"site-packages\\requests\\api.py\", line 60, in request\n  File \"site-packages\\requests\\sessions.py\", line 510, in request\n  File \"site-packages\\requests\\sessions.py\", line 453, in prepare_request\n  File \"site-packages\\requests\\models.py\", line 313, in prepare\n  File \"site-packages\\requests\\models.py\", line 387, in prepare_url\nrequests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?", 
    "url": null, 
    "save_path": null
}
```
I don't know why the `url` for a perfectly normal an visitable url is being set to `null`.

**Comment by thany** [comment]
Maybe so, but 2.3.4 is the latest stable version... I'm not seeing a stable 3.x release, unless there's something I'm missing.

**Comment by thany** [comment]
@MalloyDelacroix Can you comment on the above please? A stable 3.x release and such?
Otherwise am I not totally correct in using 2.3.4, as that's latest version that was declared stable?

**Comment by MalloyDelacroix** [comment]
The 3.x versions are technically in beta, but they only remain so because of issue #234 which falsely flags the app as a virus on Windows.  The newest release is stable in all regards but that, and that issue appears to be intermittent.
