### ISSUE TITLE
Unable to Connect to Account

### ISSUE THREAD

**Issue by bsather48** [MalloyDelacroix/DownloaderForReddit#249]
I am unable to connect to my reddit account.

I am using the following version: "v3.12.0-beta"

The error I receive is: 

bad request (reddit.com)
you sent an invalid request

— invalid redirect_uri parameter.

**Comment by ultimateakash** [comment]
Yes, I am also facing same issue.

**Comment by MalloyDelacroix** [comment]
This was due to a configuration error with the way the app was registered with reddit.  This should be fixed and will not require an update.
