### ISSUE TITLE
Imgur Credits not refreshing

### ISSUE THREAD

**Issue by Chrisnetika** [MalloyDelacroix/DownloaderForReddit#26]
Credits not refreshing at the designated time unless you reload the app.

Ver 2.3.0-master
PY 2.7.0-windows stable

**Comment by MalloyDelacroix** [comment]
This issue has been fixed.  For future reference, you should use python version 3.6 to run the application.  That is the version it is built on.  Using a version below 3 will most likely result in errors when running at some point.

**Comment by Chrisnetika** [comment]
it's 3.7.0 i'm running sorry typo
