### ISSUE TITLE
Adding a Dark Theme for the app?

### ISSUE THREAD

**Issue by Proutbedaine** [MalloyDelacroix/DownloaderForReddit#272]
I think there's not enough app that offer this now that we're in 2021, but a dark theme for any app should be a standard no? I mean, I do admit I have no idea how hard it can possibly be to do such a thing. Let's say, make it look like GitHub for example! I think this is one of the best example of color pallet for a dark theme and how they use it too; but doing something like that for these kinds of app, is it possible? And if so how hard is it?

Because personally I would highly appreciate it to be a thing. I really like to use this app full screen. The thing is though, I'm on a QLED 55" that can get REALLY bright if everything is white. With dark themes and any other stuff (movies, YouTube, gaming) the level of brightness is perfect and make every color pop. But then, when I fall on something I really wanna use fullscreen or even half-screen that is overly white, it burns both my and my girlfriend's retinas hahaha. So yeah it's not the best. Especially since I tend to be a nigh owl so I'm in the dark and it gets pretty intense at times how the backlash from going to everything very dark to a super bright white screen all of a sudden hahaha.

So yeah if any of you would know if it'd be a possibility and also if it's something hard to do in general it'd be amazing please! <3

**Comment by MalloyDelacroix** [comment]
I'm closing this because I believe it is better suited for the discussions section, where there is already a discussion started.
