### ISSUE TITLE
Is there a headless command-line mode or any way to trigger DLs without clicking?

### ISSUE THREAD

**Issue by sleaze** [MalloyDelacroix/DownloaderForReddit#274]
Firstly: Thank you for making DownloaderForReddit - it's truly a fabulous project!

Is there a way to run DownloaderForReddit in a headless mode from the command-line?  Ideally I'd like to be able to not have to click through the UI every time (e.g. schedule via cron somehow).

If this is not currently feasible (and there are no plans to support it), do you know of any way to trigger the download action for a either a single user / subreddit, or for all users / subreddits from the command-line without needing to click?

Would also be great if there was a way to suppress all pop-up dialogs, sometimes DL4R can go a little crazy when some accounts / subreddits get deleted or banned.

Thanks again!

Sincerely yours,
Mr. S

**Comment by zacker150** [comment]
There's currently no command line option for downloading individual lists, but you should be able to handle your use case by automatically launching DFR and using the scheduled downloads options.

![image](https://user-images.githubusercontent.com/7518668/151274624-ce9e8c91-38ba-4e5c-94cd-0f53df4c58ad.png)

**Comment by sleaze** [comment]
Got it, thanks Zacker150!

**Comment by sleaze** [comment]
A CLI would be super awesome, but I understand it is probably non-trivial.  I poked at it, and.. it seems like a bit of a tangle with everything being driven and scheduled by the UI.
