### ISSUE TITLE
#jpg Being Appended

### ISSUE THREAD

**Issue by Chrisnetika** [MalloyDelacroix/DownloaderForReddit#28]
#jpg being appended to all pictures (jpgs) that is on i.redd.it

Ver: 2.3.0-master commit: 4a321df5fe9a72e7f778e7799aca0ff4fcf21dcf
Python: 3.7.0-windows

**Comment by MalloyDelacroix** [comment]
I believe this issue has been fixed.  If the problem persists, please reopen the issue.
