### ISSUE TITLE
Limited number of posts are being downloaded for a user

### ISSUE THREAD

**Issue by ghost** [MalloyDelacroix/DownloaderForReddit#281]
**Describe the bug**
So I changed the download settings here 

![Capture](https://user-images.githubusercontent.com/96115036/155281073-5ee9c91e-7905-480f-857d-dc3f06d02a65.PNG)

And I tried to download all the posts from a particular user and only 72 posts are being downloaded and not all. The user has 100's of posts. I tried for different user who had 934 posts and it's the same but it downloads more than half the amount of total number of posts which was 634 and it's all reddit based posts not on imgur or any other platform based.

which 
**Environment Information**
 - Operating system : windows 10
 - Software version [e.g. 2.3.0] : 3.14.0 the latest one
 - Are you running a compiled version or from source? compiled version from releases section

**To Reproduce** (optional)

**For all but the most trivial of issues, please attach the latest log file.**
Log file below:
{
    "levelname": "INFO",
    "asctime": "02/23/2022 01:26:21 PM",
    "filename": "migration.py",
    "module": "migration",
    "name": "DownloaderForReddit.DownloaderForReddit.database.migration",
    "funcName": "check_migration",
    "lineno": 46,
    "message": "Migration not performed: no version information found in database.  Database entryfor version v3.14.0 has been created."
}
{
    "levelname": "INFO",
    "asctime": "02/23/2022 01:26:23 PM",
    "filename": "settings_manager.py",
    "module": "settings_manager",
    "name": "DownloaderForReddit.DownloaderForReddit.persistence.settings_manager",
    "funcName": "load_config_file",
    "lineno": 407,
    "message": "No config file found.  Generating new file"
}
{
    "levelname": "INFO",
    "asctime": "02/23/2022 01:26:23 PM",
    "filename": "downloader_for_reddit_gui.py",
    "module": "downloader_for_reddit_gui",
    "name": "DownloaderForReddit.DownloaderForReddit.gui.downloader_for_reddit_gui",
    "funcName": "log_startup",
    "lineno": 295,
    "message": "Application started",
    "dfr_version": "v3.14.0",
    "platform": "Windows-10-10.0.19044-SP0",
    "account_connected": false
}
{
    "levelname": "INFO",
    "asctime": "02/23/2022 01:29:00 PM",
    "filename": "downloader_for_reddit_gui.py",
    "module": "downloader_for_reddit_gui",
    "name": "DownloaderForReddit.DownloaderForReddit.gui.downloader_for_reddit_gui",
    "funcName": "run",
    "lineno": 635,
    "message": "Download thread started"
}
{
    "levelname": "INFO",
    "asctime": "02/23/2022 01:30:15 PM",
    "filename": "video_merger.py",
    "module": "video_merger",
    "name": "DownloaderForReddit.utils.video_merger",
    "funcName": "merge_videos",
    "lineno": 90,
    "message": "Video merger complete",
    "videos_successfully_merged": 0,
    "videos_unsuccessfully_merged": 0
}
{
    "levelname": "INFO",
    "asctime": "02/23/2022 01:30:15 PM",
    "filename": "download_runner.py",
    "module": "download_runner",
    "name": "DownloaderForReddit.DownloaderForReddit.core.download_runner",
    "funcName": "finish_messages",
    "lineno": 484,
    "message": "Download complete",
    "download_time": "1 min, 14 secs",
    "significant_user_count": 1,
    "significant_subreddit_count": 0,
    "total_user_count": 61,
    "total_subreddit_count": 1,
    "post_extraction_count": 72,
    "comment_extraction_count": 0,
    "download_count": 72
}

------------------------------------------------------------------------------------------------------------

**Note:** All issues marked with the **Information Needed** label will be closed after 30 days if no information is provided.

**Comment by MalloyDelacroix** [comment]
The list that you have selected in your screenshot is a "master list".  This list controls the defaults that will be set when you create a new user/subreddit list.  If you have already created a list, then changed the settings in the master list, the changes will not be forwarded to the already existing list.

In that same dialog, if you select the "Default [USER]" list, you can make the changes you want and each user added to the list afterward will have the same settings.  If you want the changed settings to take effect in users already in the list, check the "Cascade changes" checkbox in the top left.

This may help your issue if the post limit for the existing list is less than you are needing.  Since you have already run a download for the user, you will have to uncheck the "limit by date" checkbox to make sure older posts will be downloaded after you increase the limit.

Let me know if this does not solve the issue.
