### ISSUE TITLE
Download Videos setting ignored

### ISSUE THREAD

**Issue by Chrisnetika** [MalloyDelacroix/DownloaderForReddit#29]
download videos checkbox being ignored in user settings page with "do not overwrite override these settings" checked.
It still tries to download videos even if I set the user not to

Ver: 2.3.0-master commit: 4a321df
Python: 3.7.0-windows

**Comment by MalloyDelacroix** [comment]
I can't get this to reproduce.  When you say it is downloading the videos, is it actually downloading the file or are you going by the youtube-dl log output?  For the time being video links from youtube-dl supported websites are still extracted, but if download videos is not checked they will not be downloaded.  Their being extracted is what produces the log message.

If this is not the problem, do the files have a .mp4 extension?  .gif and .webm files are classified as images by the downloader.  There is a plan for a future version to support separateing these extensions into a gif category and allow disabling their download.  But this will likely not come until version 3.0.

**Comment by MalloyDelacroix** [comment]
This is an old issue without followup, so I am assuming it is not still an issue.  If this problem persists, please reopen this issue.
