### ISSUE TITLE
3.14.1 can't save the settings

### ISSUE THREAD

**Issue by 7peanuts** [MalloyDelacroix/DownloaderForReddit#290]
After restarting the software, the settings are restored to default, such as the save location, date format, etc.

**Environment Information**
 - Windows 11 21H2
 - Software version [3.14.1]
 - DownloaderForReddit_v3.14.1.zip

**Comment by MalloyDelacroix** [comment]
Can you attach your latest log file?

**Comment by 7peanuts** [comment]
> Can you attach your latest log file?

Where is the log file location?

**Comment by MalloyDelacroix** [comment]
It looks like there is an encoding problem in your settings file at the start of the user save directory path.  Have you edited the config file directly in a text editor?

**Comment by 7peanuts** [comment]
> It looks like there is an encoding problem in your settings file at the start of the user save directory path. Have you edited the config file directly in a text editor?

Yes, I deleted the previous logs, I will upload again.

**Comment by MalloyDelacroix** [comment]
Fixed by pull request #299
