### ISSUE TITLE
a way to stitch downloaded videos ?

### ISSUE THREAD

**Issue by lamasterso** [MalloyDelacroix/DownloaderForReddit#292]
Can I stictch downloaded videos to make 15 minute long videos if videos are less than 15 minute it automatically Combines multiple videos to make 15 minute atleast, Is this possible with FMMPEG ?

**Comment by MalloyDelacroix** [comment]
This is not possible with the Downloader for Reddit.  I'm not sure if it is possible with FFMPG.  [Here is a link to their documentation](https://ffmpeg.org/documentation.html).
