### ISSUE TITLE
Redgifs extractor not pulling

### ISSUE THREAD

**Issue by saltnpap** [MalloyDelacroix/DownloaderForReddit#302]
**Describe the bug**
```
Error message: Failed to retrieve json data from link
Title: [title]
Url: [redgif url]
```

**Environment Information**
 - Operating system: W10 64bit
 - Software version [e.g. 2.3.0]  v3.14.2
 - Are you running a compiled version or from source? Compiled version (GUI)

**Comment by MalloyDelacroix** [comment]
I can't reproduce this error.  Is it possible the link has been deleted or is otherwise inaccessible?

If this is not the case, I will need the log file to diagnose the problem.

**Comment by saltnpap** [comment]
I had a VPN running and the tokens accessed via browser weren't the same. Turning it off seemed to fix it.
