### ISSUE TITLE
Not properly carrying over imgur downloads

### ISSUE THREAD

**Issue by Chrisnetika** [MalloyDelacroix/DownloaderForReddit#31]
idk best way to title this but here the issue,app I know is designed for any reason it cannot download an imgur imgage because of credits,over capacity or etc what happens(or should happen) is that link get saved for next download run.So when you download again it should get the image it could not get for some reason last time.In this version I believe that is not properly working .Imgur images that fail to download do not download next run, but prob is that it triggers a crash as described in issue #21  and #27  .Crash triggers right away making the user undownloadable. Only way to fix it is to remove user then readd user and redownload that user..

Steps to reproduce
1- start with very low imgur credits
2- add a user (that has imgur images more than your credits)
3- open user
4- download
5- crash

Version- 2.3.0 -master
commit- 49a38be543bc9346f63312951fb971bb941bd714

python- 3.7.0-windows stable

**Comment by MalloyDelacroix** [comment]
Can you attach the log for this?

**Comment by Chrisnetika** [comment]
Today when I did a total download of all users I got a few msgs of "imgur over capacity" , when I try to manually download one of the users affected I get that crash
https://imgur.com/a/GNyGAjh

This is a result of the downloader tryig to carry over imgur downloads not working right

**Comment by Chrisnetika** [comment]
when I do a total download of all users not just manual download of affected users the crash happens too.. bad crash.Now I have to remove those users and readd them to be able to use the program

**Comment by MalloyDelacroix** [comment]
I believe this issue is fixed.  If it still persists, please reopen the issue.
