### ISSUE TITLE
I still get the RedGifs error in the latest version

### ISSUE THREAD

**Issue by Amitoth** [MalloyDelacroix/DownloaderForReddit#322]
**Describe the bug**
The RedGifs download error still exists in the latest version

**Environment Information**
 - Windows 10
 - Software version 3.15.2
 - Running from source
 
**To Reproduce** (optional)
1. Go to any Reddit profile with RedGifs uploads
2. Click on Download
3. 
![NSFW](https://user-images.githubusercontent.com/117578919/200173006-5dedb02b-013f-4c00-8421-8fc478cc9995.PNG)
5. See error

Am I doing something wrong?

**Comment by saltnpap** [comment]
Also not able to download from redgifs.

Thanks again, Malloy for working on this. Your work is well appreciated.

**Comment by T-prog3** [comment]
I have noticed failed extractions as well. In my case most video files gets downloaded, only had one or two that didn't. Most of the error messages appears to be because of broken links, but i have also seen a lot of false-positives on URLs containing images.

**Comment by MalloyDelacroix** [comment]
Alright, this one was on me.  You aren't actually failing to download those links.  They are failing the content filter, most likely because they are duplicates.  There was an error in the code that reported these as failures to extract.

**Comment by Amitoth** [comment]
Thanks Malloy for getting this fixed!
