### ISSUE TITLE
Download failed due to disk full mid download, issue with resuming downloads after making space

### ISSUE THREAD

**Issue by OrpheusXx** [MalloyDelacroix/DownloaderForReddit#326]
Hello, my download haven't finished because my disk became full mid download, so i stopped the program.
Made space on that same disk, opened up the program, press start download user and there is nothing to download.
I know there is something to download, but for some reason the program thinks it's already downloaded.
Any way to fix this?

**Comment by MalloyDelacroix** [comment]
Most likely what happened is that the posts were already extracted when you stopped the download.  So when another session starts, it does not see any new content to extract and download.

You can download content that has already been extracted but not downloaded by clicking "Run Unfinished Downloads" under the download tab.
