### ISSUE TITLE
Imgur Credits Draining on their own

### ISSUE THREAD

**Issue by Chrisnetika** [MalloyDelacroix/DownloaderForReddit#33]
I noticed this just now, with nothing going on credits go down on their own

https://imgur.com/a/CTyT6VP

ver- 2.3.0-master
commit- 9f1f509e2ffcc7285f3cb9d7d2d16dab51859238
python- 3.7.0-windows stable

**Comment by MalloyDelacroix** [comment]
This is most likely not an issue with the downloader itself.  If the downloader is not running, there is no way it can be consuming imgur credits.  I would say this is most likely something to do with the imgur api.  It may take it a few moments to catch up to the credits that have been consumed previously.  This application does not keep track of the imgur credits that have been used or handle the actual credits themselves in any way.  All credit tracking and use is done by the imgur api and the available credits are stored on their system.  Whenever you check your imgur credits through this app, a call is made to the imgur api to retrieve this data.

This would also be affected if you are using the same imgur client id and secret for other applications or interactions with imgur or if you have multiple instances of this application running.
