### ISSUE TITLE
Running with a fresh environment doesn't work anymore

### ISSUE THREAD

**Issue by Auravendill** [MalloyDelacroix/DownloaderForReddit#333]
Creating a new Python environment and trying to run main.py fails.

I first created a fresh new environment with conda create -n reddit python=3

activated the environment with conda activate reddit

and installed all the requirements into it via python3 -m pip install -r requirements.txt

But when I try to run main.py, I get:

asctime: 01/31/2023 11:51:37
levelname: CRITICAL
name: DownloaderForReddit.__main__
message: Unhandled exception
exc_info: Traceback (most recent call last):
  File "/home/daniel/Git/DownloaderForReddit/main.py", line 104, in <module>
    main()
  File "/home/daniel/Git/DownloaderForReddit/main.py", line 77, in main
    window = DownloaderForRedditGUI(queue, receiver, scheduler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/Git/DownloaderForReddit/DownloaderForReddit/gui/downloader_for_reddit_gui.py", line 90, in __init__
    self.spinner = WaitingSpinner(self.user_list_view, roundness=80.0, opacity=10.0, fade=72.0, radius=10.0,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/envs/reddit/lib/python3.11/site-packages/pyqtspinner/spinner.py", line 60, in __init__
    self.updateSize()
  File "/home/daniel/miniconda3/envs/reddit/lib/python3.11/site-packages/pyqtspinner/spinner.py", line 204, in updateSize
    self.setFixedSize(size, size)
TypeError: arguments did not match any overloaded call:
  setFixedSize(self, QSize): argument 1 has unexpected type 'float'
  setFixedSize(self, int, int): argument 1 has unexpected type 'float'

**Comment by MalloyDelacroix** [comment]
What version of Python are you using?

**Comment by Auravendill** [comment]
I had tried 3.11 3.10 and 3.9 (and 3.6, since that used to be what the documentation asked for, but that failed differently). Now the documentation is updated and 3.8 seems to work good enough.
