### ISSUE TITLE
Crash during download

### ISSUE THREAD

**Issue by Chrisnetika** [MalloyDelacroix/DownloaderForReddit#35]
not related to other crash in issue #21 
happened during downloading
log: https://imgur.com/a/N8pKTFB
version: 2.3.1?-master
commit: 3ec6f1ea96da65cb5337dfdce46940069fa5b683
python: 3.7.0-windows stable

**Comment by Chrisnetika** [comment]
been also getting alot of this lately with newest commit
https://imgur.com/a/9vTbna9

**Comment by MalloyDelacroix** [comment]
Your comment says that this issue is not related to issue #21, but the error message in your log screen-cap is the exact same message and I believe these are the same issue.  I am closing this issue as a duplicate of #21.
