### ISSUE TITLE
Need docs for how to run the tests

### ISSUE THREAD

**Issue by crccheck** [MalloyDelacroix/DownloaderForReddit#37]
Some code assumes you're running from the `DownloaderForReddit/` directory, but the tests are then in `../Tests`. There's lots of other weird things that prevent the normal ways of getting `python -m unittest` from being able to discover and run the tests.

I can get tests to start running if I'm in the project root and do `PYTHONPATH=DownloaderForReddit/ python -m unittest` but then I'm in the wrong directory for `open(supported_sites_file, 'r')` to work.

**Comment by MalloyDelacroix** [comment]
The project has been restructured to solve a lot of the problems related to this issue.  Now both the app and tests are run from the main DownloaderForReddit directory (not the DownloaderForReddit sub directory).  

The "Setting Up A Development Environment" wiki page has been updated to reflect this and add a line about running the tests.  New extractor package tests have also been added.
