### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by darhanger** [MalloyDelacroix/DownloaderForReddit#372]
![image](https://github.com/MalloyDelacroix/DownloaderForReddit/assets/22445395/190f22e0-594a-4efd-81f1-da8fcbc85f83)

**Comment by MalloyDelacroix** [comment]
It looks like something went wrong with the automated build.  I'm not sure what happened, but I have removed the problem .zip and replaced it with a working one.  Reopen this if the issue persists.
