### ISSUE TITLE
OFF TOPIC: Quick question.. about Twitter

### ISSUE THREAD

**Issue by EC-O-DE** [MalloyDelacroix/DownloaderForReddit#43]
Quick question.. about Twitter

Does anyone know a an app similar to this but for Twitter?

**Comment by Multiboxer** [comment]
The "Twitter Media Downloader" extension for Chrome or Firefox is very powerful for downloading media from a user especially when you combine it with Twitter's search functionality. For example a benefit of combining this extension with search functionality you can add users to a private twitter list and then search `Filter:media list:@UserName/ListName` or another example `Filter:media #News` However I cannot guarantee it will return all possible results as there are varying limits on how many results appear on a twitter search. Also note if the downloading is interrupted you can use tweet IDs to determine where to resume or end the desired download. I hope this helps!

**Comment by EC-O-DE** [comment]
I use that ext but didn't knew of this other possibility!

**Comment by EC-O-DE** [comment]
I have found this but it's hard! :(
https://github.com/ScriptSmith/reaper
