### ISSUE TITLE
"A save file could not be created..." error when loading old config

### ISSUE THREAD

**Issue by mavrc** [MalloyDelacroix/DownloaderForReddit#49]
I have been receiving errors after updating from DFR 2.22 to 2.3x - I have tried 2.31 and 2.32. OS Win10. To find the tidiest way to duplicate this problem here's what I did:

 - deleted %appdata%\Roaming\SomeGuySoftware\DownloaderForReddit
 - started DFR
 - asked it to import save file from an old copy I had on my desktop
 - confirmed overwrite

After overwrite this error immediately appears, and it also appears if the app is closed and reopened:

![image](https://user-images.githubusercontent.com/3488307/50116457-7146c200-0207-11e9-980d-6a13bb3a9f60.png)

If the config directory is purged completely and a new config is created, the app works fine. 

See attached log: 
[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/2687878/DownloaderForReddit.log)

**Comment by MalloyDelacroix** [comment]
Usually this particular error occurs if you have saved content or saved posts for either users or subreddits.  Can you check each user or subreddit in your list (hopefully it's not a large list) and see if they have any saved posts or submissions?  

If you go to user or subreddit settings via context menu and right click on the previous downloads box, you can select to display either saved posts or submissions and clear them.  Try clearing these lists and see if that resolves the issue.  I recommend copying the save file to another location for backup first, in case this does not solve the issue, you will not lose your saved items.

**Comment by MalloyDelacroix** [comment]
@bababap This appears to be the same issue.  Do you have any saved posts or content in any of the users or subreddits in the save file you are trying to load?  Also, are you running on Windows or Linux?
