### ISSUE TITLE
Url domain not supported

### ISSUE THREAD

**Issue by partyhatbowtieguy** [MalloyDelacroix/DownloaderForReddit#53]
Trying to download but I'm getting an error on particular imgur posts. https://i.imgur.com/xxxxxxx.jpg and https://imgur.com/a/xxxxxx. I suspect it might be the https if that's the case can it be updated to include that or is there some way I can turn the https off in the program.

**Comment by MalloyDelacroix** [comment]
This problem shouldn't be caused by https being in the url.  I will have to see the log to diagnose the problem.
