### ISSUE TITLE
Not downloading posts

### ISSUE THREAD

**Issue by vv211** [MalloyDelacroix/DownloaderForReddit#55]
The program won't download media for new users/subreddits. I have added several new users to my list, and added a subreddit to test that as well. This was originally occurring on 2.3.0, updating to 2.3.2 did not resolve the issue

Are there logs saved somewhere that I can look at?

**Comment by MalloyDelacroix** [comment]
Yes, you can access the log by going to File -> Open Save Location.  It should be in
"AppData/Roaming/SomeGuySoftware/DownloaderForReddit/"

**Comment by vv211** [comment]
I've searched through the logs and no results returned for the usernames and subreddits which are failing to download

Failed usernames are:
dare_to_share
hisandhersecret2018
sexymooncake
mbogxmbor

failed sub:
alahnaly_

[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/2742299/DownloaderForReddit.log)

[DownloaderForReddit1.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/2742303/DownloaderForReddit1.log)

**Comment by MalloyDelacroix** [comment]
From the log I see that you have the download set to download only user posts that are in the subreddits in the subreddit list, and that you only have one subreddit in that list.  Are you sure that the users you are trying to download have posted in that subreddit?

**Comment by vv211** [comment]
They have not; Does having both the "Download users" and "Download subreddits" boxes checked mean to only download posts from a subreddit that have been submitted by the users in the list? I thought I could download all posts in a sub regardless of author, and that the subreddit list was used for that. 

The new users weren't downloading even before I added a sub. I had added that to test if that would fail as well. I must have been doing something different at that point because users are downloading correctly now, with subreddit unchecked as you suggested.

**Comment by MalloyDelacroix** [comment]
Right, If both check boxes are checked, only user posts in subreddits in the subreddit list will be downloaded.  If only the user checkbox is checked, the user content will be downloaded regardless of sub.  If only the subreddit checkbox is checked, the subreddit content will be downloaded regardless of user.
