### ISSUE TITLE
Failed to download content

### ISSUE THREAD

**Issue by drandreaskrueger** [MalloyDelacroix/DownloaderForReddit#59]
I get a lot of these:
```
Failed to download content:
User: ******  Subreddit: ***  Title: ***
Url:  https://www.reddit.com/r/****/comments/****/**********/
Failed to locate content
Save Status: Not Saved
```

It does find all of my posts - great. But then it cannot download that content.

what to do.

**Comment by drandreaskrueger** [comment]
Some are 

    Status Failed to locate content

some others are

    Status Failed to extract post: Url domain not supported

yet others are

    Status Unrecognized extension

**Comment by drandreaskrueger** [comment]
```
rm ~/.config/SomeGuySoftware -rf
./DownloaderForReddit 

Unable to update the static FcBlanks: 0x0600
Unable to update the static FcBlanks: 0x0601
Unable to update the static FcBlanks: 0x0602
Unable to update the static FcBlanks: 0x0603
Unable to update the static FcBlanks: 0x06dd
Unable to update the static FcBlanks: 0x070f
Unable to update the static FcBlanks: 0x2028
Unable to update the static FcBlanks: 0x2029
Unable to update the static FcBlanks: 0xfff9
Unable to update the static FcBlanks: 0xfffa
Unable to update the static FcBlanks: 0xfffb
message: First run of new version
old_version: v0.0.0
name: DownloaderForReddit.DownloaderForReddit.Persistence.SettingsManager
levelname: INFO
new_version: v2.3.2
asctime: 03/20/2019 01:40:52 am

message: Failed to load from save file
name: DownloaderForReddit.DownloaderForReddit.Persistence.ObjectStateHandler
levelname: ERROR
save_file_location: ~/.SomeGuySoftware/DownloaderForReddit/save_file
exc_info: Traceback (most recent call last):
  File "shelve.py", line 111, in __getitem__
KeyError: 'user_list_models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DownloaderForReddit/Persistence/ObjectStateHandler.py", line 62, in load_pickled_state
  File "shelve.py", line 113, in __getitem__
KeyError: b'user_list_models'
asctime: 03/20/2019 01:40:52 am

message: Load state error: No save file found
exc_info: Traceback (most recent call last):
  File "DownloaderForReddit/GUI/DownloaderForRedditGUI.py", line 1296, in load_state
TypeError: 'NoneType' object is not subscriptable
name: DownloaderForReddit.DownloaderForReddit.GUI.DownloaderForRedditGUI
asctime: 03/20/2019 01:40:52 am
levelname: ERROR
```

**Comment by drandreaskrueger** [comment]
then I've created a user list, and a user, and it changes to:

```
./DownloaderForReddit 
Unable to update the static FcBlanks: 0x0600
Unable to update the static FcBlanks: 0x0601
Unable to update the static FcBlanks: 0x0602
Unable to update the static FcBlanks: 0x0603
Unable to update the static FcBlanks: 0x06dd
Unable to update the static FcBlanks: 0x070f
Unable to update the static FcBlanks: 0x2028
Unable to update the static FcBlanks: 0x2029
Unable to update the static FcBlanks: 0xfff9
Unable to update the static FcBlanks: 0xfffa
Unable to update the static FcBlanks: 0xfffb
name: DownloaderForReddit.DownloaderForReddit.Persistence.ObjectStateHandler
levelname: INFO
updated_subreddits: 0
message: Object lists loaded from save file
updated_users: 0
total_users: 1
asctime: 03/20/2019 01:44:44 am
total_subreddits: 0

name: DownloaderForReddit.DownloaderForReddit.GUI.DownloaderForRedditGUI
levelname: INFO
message: Save_file successfully loaded into gui
asctime: 03/20/2019 01:44:44 am
```

**Comment by drandreaskrueger** [comment]
then I set a save folder ...

as mentioned above, it does find 25 of my comments, but then does not download them, with the above given status messages.


I just want to download all my own comments on reddit. not more. please help.

**Comment by MalloyDelacroix** [comment]
There are actually a couple of issues here.  The first being that at this time the Downloader For Reddit does not support downloading self posts or comments.  It will only download media links from supported host sites.  Version 3.0, which is currently under development, will support downloading self posts and comments.  My goal is to have it released by mid-year.

The second issue is related to save file migration on Linux systems.  This issue only occurs when a save file is created with an older version of the app, and then loaded from the new version.  This is an issue that I have been aware of, but only occurs on one of the three Linux machines I use to test the app and I have been unable to solve as of yet.  Version 3.0 will have a new storage backend that I hope will solve this issue as well.

Since these issues are already referenced elsewhere, I will close this issue.

**Comment by drandreaskrueger** [comment]
Ah, thanks.

Misunderstanding from my side.

What about making the purpose of your tool a bit clearer in the README:

> Downloader for Reddit is a GUI application for downloading content submitted to reddit. 

--> perhaps like this:

> Downloader for Reddit is a GUI application for downloading content (images, videos) submitted to reddit. Currently it does not download posts or comments yet, that is planned for a future version of DownloaderForReddit.

?

Thanks a anyways for the infos. 

Feel free to post a short message here when 3.0 is released, then I am happy to try it out.


Thanks.
