### ISSUE TITLE
Windows - reports old version, crashes when trying to remove list

### ISSUE THREAD

**Issue by Mike-EE** [MalloyDelacroix/DownloaderForReddit#6]
Hi -

Windows 7 (DFR version unkown, ZIP named 2.0.2 but the Help>About reports 2.0)

Also, I can't remove lists as the app will crash (Windows appcrash dialog).

Let me know if you need additional information.

Thanks!

**Comment by MalloyDelacroix** [comment]
Both of these issues have been fixed.  They will be included in v2.0.3 which will be release very soon.
