### ISSUE TITLE
UI elements missing

### ISSUE THREAD

**Issue by SaiKDot** [MalloyDelacroix/DownloaderForReddit#60]
the drop down menu, and the add user list are missing from the window.
I've deleted the save folder and installed fresh, the issue still persists.

![dfr-error](https://user-images.githubusercontent.com/37064405/55935285-d8720180-5c50-11e9-8fae-b0965891fc3f.PNG)

**Comment by MalloyDelacroix** [comment]
The lower portion of the UI is just hidden at the bottom.  Position your mouse at the bottom of one of the white windows until the cursor changes, then drag up.
