### ISSUE TITLE
There are no user lists available

### ISSUE THREAD

**Issue by thany** [MalloyDelacroix/DownloaderForReddit#62]
Getting this error when trying to add a subreddit:

> There are no user lists available. To add a user, please add a user list

Okay. I don't want to add a user. But if I must add a user list (what is that anyway?) so I shall.
Now to figure out how to add this user list...

Some time passes.

Got it. I think.

Try again. Same error message. Maybe it wants me to add a user? At least that works. I don't understand why it's a + button, and not just a button that says "Add user", but oh well. Someone didn't read up on UX design. That's fine.

Anyway, back to adding subreddits.

Same error. Or warning actually, but even a warning is blocking me so I guess it's meant as an error.

Now what?...

**Comment by MalloyDelacroix** [comment]
That error message is the same message used for both user and subreddit lists.  I see that I do need to switch the nouns when the error originates from the subreddit list though.  Sorry for the inconvenience.

As for your problem with the UI design:  large buttons with words take up more UI real estate than small tool buttons, and this is designed to be a small window app.  I didn't imagine this would be a problem as "+" is universally synonymous with "add", but I suppose there are always outliers that don't understand.

Thanks for bringing the error message language to my attention, albeit quite rudely.  It will be fixed for the next release.

**Comment by thany** [comment]
> I didn't imagine this would be a problem as "+" is universally synonymous with "add"

This is true, but "add what"? There are two thingies to add there; a list or an item in that list.

Wasn't meant to be rude though. Sorry that it came through that way. I just sort of wrote down my journey towards getting things to work.
