### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by thany** [MalloyDelacroix/DownloaderForReddit#63]
I managed to download a user (I think), but the download button doesn't do as promised.

When I press Download, nothing appears to happen, other than the text on the button changes. "Click to Stop Download". Okay, so it's a start/stop button. You don't need to put a whole paragraph of text on the button for that ;)

Anyway, nothing happens when I click it to stop the download. Well, something happens: "Stopped" is added to the list beneath it. And several more for each time I click it. Only 10 seconds or so later, it claims to have finished. Why? I clicked the stop button, didn't I? Why did it not stop?

**Comment by MalloyDelacroix** [comment]
This has all been discussed in other issues.  As stated in issue #57, this stop behavior has been changed on the master branch and will take effect in the next release.
