### ISSUE TITLE
It just closed?

### ISSUE THREAD

**Issue by thany** [MalloyDelacroix/DownloaderForReddit#64]
Finally got it to do stuff. I got it to download one subreddit. Bingo.

So I added a bunch more, and hit the download button, and then went on to do something else. It appeared to be working anyway, so why keep watching it, right?

Half an hour or so later, I found that the application had closed, presumably. It hadn't downloaded a single image, and upon starting it again, it also hasn't rememberd all the subreddits I added. It has also forgotten the imgur codes I needed to add.

What gives? I would expect I find an error message or something, if somethig has catastrophically exploded, so I could post that here and it might be useful. But now, this is all I can say.

**Comment by MalloyDelacroix** [comment]
To persist added users, subreddits, settings, imgur codes, etc. you must save the application.  The save button can be found in the file menu.  I recommend saving before starting a download.

Sometimes applications crash for unexpected reasons.  The useful message you are looking for can most likely be found in the application log.  I will need the log to diagnose the problem you are experiencing here.

**Comment by thany** [comment]
If you can let me know where to find the log, that'd be very helpful when I decide this give this program another go. It is, after all, a while ago, but maybe I'll get around to it sometime this week.

**Comment by MalloyDelacroix** [comment]
On Windows it's in "AppData\Roaming\SomeGuySoftware\DownloaderForReddit",  on Linux its in "~/.SomeGuySoftware/DownloaderForReddit".  

You can get there through the app if you go to File then click "Open Save Location".  The save file and the log are stored in the same location.
