### ISSUE TITLE
Sample pyinstaller spec missing

### ISSUE THREAD

**Issue by zacker150** [MalloyDelacroix/DownloaderForReddit#66]
In the contributing guidelines, it says

> See the sample .spec file for packaging with pyinstaller.

However, there is no sample .spec file in the repo. Can you upload a sample .spec file used to package the releases?

**Comment by MalloyDelacroix** [comment]
I have added the sample.spec file.  I have noted, however, that the spec file usually needs to be tuned to run on a specific machine.  This is usually a trial and error process to make sure everything in the "pathex" list is correct.

Just in case you run into it, I have also noticed on some machines it does not pick up PyQt5.sip.  If this happens to be the case, just add "PyQt5.sip" to the hiddenimports list in the spec file.
