### ISSUE TITLE
Scanning of previously DL'd data?

### ISSUE THREAD

**Issue by EC-O-DE** [MalloyDelacroix/DownloaderForReddit#7]
I'm not quite sure does that work, it seems that every time DFR dl's a bunch of duplicates... :/

Then again I had Reddit Data Ext before DFR and I didn't delete old content...

I'm using a tool to find exact duplicates after DL with DFR to sort out _old_ duplicates compared to _new_.

Hmm I'm not sure ~ perhaps RDE has few moe settings to fine tune. That client either doesn't 'find' other clients data as something of previous.

**Comment by MalloyDelacroix** [comment]
Downloader for Reddit attempts to avoid duplicates in two ways.  

First, it sets the last downloaded date for a user or subreddit to the latest post date taken from that user or sub and will not download anything posted before that date during subsequent runs. 

The other way is that it keeps a list of every url that it downloads and will not download the same url twice with one caveat.  The urls are tracked per user or subreddit.  So if say a link is posted to pics that is also posted to earthporn at the same url, the downloader will not detect that and will download both.

The other instance of duplicate content downloads that I have found is that sometimes the same image is posted to a subreddit multiple times but by different users and at different urls.  There is no way to avoid this.

But as for avoiding content downloaded with another app, there is no way to automatically avoid these duplicates.  The closest thing I can recommend is that you can set DFR's 'Restrict downloads by custom date' to the date that you stopped using the other app, and it will only download posts made after that date.

**Comment by EC-O-DE** [comment]
"Restrict downloads by custom date' to the date that you stopped using the other app, and it will only download posts made after that date."

thanks for the tip!
