### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by LEIDERPRO** [MalloyDelacroix/DownloaderForReddit#70]
Hello, the downloader works but the videos are without sound...

I have installed FFmpeg but it still downloads without sound what I do wrong?

**Comment by MalloyDelacroix** [comment]
Are you building the application from source or are you running from the release executable?

**Comment by LEIDERPRO** [comment]
I used the release version.

**Comment by MalloyDelacroix** [comment]
The reddit video merger is an unreleased feature.  It is available now if you build the application from source.  Otherwise it will be in the next release of the application, which should be coming soon.

**Comment by LEIDERPRO** [comment]
Okay worked with the source version :) Thanks you
