### ISSUE TITLE
Crash While Trying to Download from Certain Subreddits

### ISSUE THREAD

**Issue by amateurbabes** [MalloyDelacroix/DownloaderForReddit#71]
I've been trying all day to download from a few subreddits and it crashes while it's... validating? I guess. It only happens when I'm trying to download from certain subreddits, and not others, which makes no sense to me. It's been crashing all day. Any idea how to fix this issue?

**Comment by zacker150** [comment]
Can you submit your log files? You should be able to find them by going to File -> Open Save Location

**Comment by amateurbabes** [comment]
Man, I was trying to figure out how to find my log files after reading up on other issues here. I'm going to assume this is the log?

[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/3439199/DownloaderForReddit.log)

**Comment by MalloyDelacroix** [comment]
It appears this issue is caused by trying to download posts that have been removed by reddit.  When the posts are removed, they are missing some attributes that are used elsewhere when they are extracted and the downloader was not handling this gracefully.

This issue should be resolved now if you are building the project from source, otherwise it will be in the next release.

**Comment by amateurbabes** [comment]
> It appears this issue is caused by trying to download posts that have been removed by reddit. When the posts are removed, they are missing some attributes that are used elsewhere when they are extracted and the downloader was not handling this gracefully.
> 
> This issue should be resolved now if you are building the project from source, otherwise it will be in the next release.

When will the next release be? Any idea?

**Comment by MalloyDelacroix** [comment]
I hadn't realized it had been over a year since the last one.  We definitely have enough for a new release right now.  I will start work on getting a new version out.  I would expect it to be just before the new year.

**Comment by amateurbabes** [comment]
> I hadn't realized it had been over a year since the last one. We definitely have enough for a new release right now. I will start work on getting a new version out. I would expect it to be just before the new year.

Great! Can't wait!

**Comment by zacker150** [comment]
Have you ever considered using a hosted continuous integration solution to automatically release upon a commit to master? 

I believe [Travis CI](https://travis-ci.com/) is free for open source projects
