### ISSUE TITLE
Allow downloads from commented imgur/erome links.

### ISSUE THREAD

**Issue by Jalawoud** [MalloyDelacroix/DownloaderForReddit#72]
**Is your feature request related to a problem? Please describe.**

The original DownloaderForReddit allowed the user to download videos/images from reddit posters who've linked imgur links in the comments. 

**Describe the solution you'd like**

Allow the option to download the media from commented imgur links, (original poster only).

**Additional context**

**Comment by MalloyDelacroix** [comment]
This is a feature that is slated for version 3.0.

**Comment by Jalawoud** [comment]
> This is a feature that is slated for version 3.0.

Not sure if this is already known, but private subreddits cause the exe to crash. Maybe allow for logging in so it has privilege?

**Comment by MalloyDelacroix** [comment]
I was not aware of this.  Thanks for bringing it to my attention.

**Comment by Jalawoud** [comment]
There's another error somewhere but I don't really have a crash log. 

https://tmpfiles.org/download/25927/2019-09-1011-59-16.flv

This video shows, that when you search for the exe through windows, and then click add user or add subreddit, it will crash. 

However, if you open the folder and launch the exe, those actions will act normally. It could be windows fault, but just throwing it out there in case.

**Comment by zacker150** [comment]
Is is possible that you have multiple versions on your computer? Try verifying that you are actually launching the same exe both ways.
