### ISSUE TITLE
Cannot import save file

### ISSUE THREAD

**Issue by EC-O-DE** [MalloyDelacroix/DownloaderForReddit#9]
I'm trying all I can... I just cant get the app to read/save imported save file  :/

**Comment by MalloyDelacroix** [comment]
Can you attach your log file?

**Comment by EC-O-DE** [comment]
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.SettingsManager", "filename": "SettingsManager.py", "module": "SettingsManager", "funcName": "check_first_run", "lineno": 62, "message": "First fun of new version", "asctime": "02/24/2018 08:09:22 PM", "new_version": "v2.1.0", "old_version": "v2.0"}
{"levelname": "ERROR", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 87, "message": "Failed to load from save file", "asctime": "02/24/2018 08:09:22 PM", "exc_info": "Traceback (most recent call last):\n  File \"shelve.py\", line 111, in __getitem__\nKeyError: 'user_list_models'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"DownloaderForReddit\\Persistence\\ObjectStateHandler.py\", line 62, in load_pickled_state\n  File \"shelve.py\", line 113, in __getitem__\n  File \"dbm\\dumb.py\", line 148, in __getitem__\nKeyError: b'user_list_models'", "save_file_location": "C:\\Users\\EC\\AppData\\Roaming\\SomeGuySoftware\\DownloaderForReddit\\save_file"}
{"levelname": "ERROR", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1321, "message": "Load state error: No save file found", "asctime": "02/24/2018 08:09:22 PM", "exc_info": "Traceback (most recent call last):\n  File \"DownloaderForReddit\\GUI\\DownloaderForRedditGUI.py\", line 1304, in load_state\nTypeError: 'NoneType' object is not subscriptable"}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "save_pickled_state", "lineno": 126, "message": "Objects successfully saved", "asctime": "02/24/2018 08:09:31 PM", "total_users_saved": 0, "total_subreddits_saved": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 83, "message": "Object lists loaded from save file", "asctime": "02/24/2018 08:09:34 PM", "total_users": 0, "total_subreddits": 0, "updated_users": 0, "updated_subreddits": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1317, "message": "Save_file successfully loaded into gui", "asctime": "02/24/2018 08:09:34 PM"}
{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename": "main.py", "module": "main", "funcName": "log_unhandled_exception", "lineno": 86, "message": "Unhandled exception", "asctime": "02/24/2018 08:10:02 PM", "exc_info": "Traceback (most recent call last):\n  File \"DownloaderForReddit\\GUI\\DownloaderForRedditGUI.py\", line 1364, in import_save_file\n  File \"DownloaderForReddit\\GUI\\DownloaderForRedditGUI.py\", line 1395, in move_save_files\nOSError: [WinError 17] The system cannot move the file to a different disk drive: 'E:/EC/PORTABLE/zbackup\\\\save_file.dat' -> 'C:\\\\Users\\\\EC\\\\AppData\\\\Roaming\\\\SomeGuySoftware\\\\DownloaderForReddit\\\\save_file.dat'"}
{"levelname": "ERROR", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 93, "message": "Failed to load from save file", "asctime": "02/24/2018 08:10:06 PM", "exc_info": "Traceback (most recent call last):\n  File \"shelve.py\", line 111, in __getitem__\nKeyError: 'user_list_models'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"DownloaderForReddit\\Persistence\\ObjectStateHandler.py\", line 62, in load_pickled_state\n  File \"shelve.py\", line 114, in __getitem__\nEOFError: Ran out of input", "save_file_location": "C:\\Users\\EC\\AppData\\Roaming\\SomeGuySoftware\\DownloaderForReddit\\save_file"}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "save_pickled_state", "lineno": 126, "message": "Objects successfully saved", "asctime": "02/24/2018 08:10:24 PM", "total_users_saved": 0, "total_subreddits_saved": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 83, "message": "Object lists loaded from save file", "asctime": "02/24/2018 08:10:29 PM", "total_users": 0, "total_subreddits": 0, "updated_users": 0, "updated_subreddits": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1317, "message": "Save_file successfully loaded into gui", "asctime": "02/24/2018 08:10:29 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "change_user_list", "lineno": 621, "message": "User list changed to: ALL", "asctime": "02/24/2018 08:10:51 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditSettingsGUI", "filename": "DownloaderForRedditSettingsGUI.py", "module": "DownloaderForRedditSettingsGUI", "funcName": "__init__", "lineno": 47, "message": "Settings dialog opened", "asctime": "02/24/2018 08:10:54 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditSettingsGUI", "filename": "DownloaderForRedditSettingsGUI.py", "module": "DownloaderForRedditSettingsGUI", "funcName": "set_imgur_client", "lineno": 201, "message": "Imgur client_id and client_secret set", "asctime": "02/24/2018 08:10:59 PM", "valid_client_id": true, "valid_client_secret": true}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditSettingsGUI", "filename": "DownloaderForRedditSettingsGUI.py", "module": "DownloaderForRedditSettingsGUI", "funcName": "save_settings", "lineno": 308, "message": "Settings saved", "asctime": "02/24/2018 08:11:24 PM", "settings": {"imgur_client_valid": true, "restrict_by_score": false, "score_limit_operator": "GREATER", "score_limit": 3000, "subreddit_sort_method": "HOT", "subreddit_sort_top_method": "DAY", "post_limit": 1000, "restrict_by_date": true, "restrict_by_custom_date": false, "custom_date": 86400, "download_videos": true, "download_images": true, "avoid_duplicates": true, "nsfw_filter": "ONLY", "save_subreddits_by": "User Name", "name_downloads_by": "Image/Album Id", "save_directory": "E:/ZE/R/", "max_download_thread_count": 4, "save_undownloaded_content": true}}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "update_user_settings", "lineno": 1048, "message": "User settings updated", "asctime": "02/24/2018 08:11:24 PM", "updated_users": 0, "total_users": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "update_subreddit_settings", "lineno": 1062, "message": "Subreddit settings updated", "asctime": "02/24/2018 08:11:24 PM", "updated_subreddits": 0, "total_subreddits": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "save_pickled_state", "lineno": 126, "message": "Objects successfully saved", "asctime": "02/24/2018 08:11:28 PM", "total_users_saved": 0, "total_subreddits_saved": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "save_pickled_state", "lineno": 126, "message": "Objects successfully saved", "asctime": "02/24/2018 08:11:30 PM", "total_users_saved": 0, "total_subreddits_saved": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 83, "message": "Object lists loaded from save file", "asctime": "02/24/2018 08:11:32 PM", "total_users": 0, "total_subreddits": 0, "updated_users": 0, "updated_subreddits": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1317, "message": "Save_file successfully loaded into gui", "asctime": "02/24/2018 08:11:32 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "change_user_list", "lineno": 621, "message": "User list changed to: ALL", "asctime": "02/24/2018 08:11:49 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "change_user_list", "lineno": 621, "message": "User list changed to: DEF", "asctime": "02/24/2018 08:11:51 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "save_pickled_state", "lineno": 126, "message": "Objects successfully saved", "asctime": "02/24/2018 08:11:54 PM", "total_users_saved": 0, "total_subreddits_saved": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 83, "message": "Object lists loaded from save file", "asctime": "02/24/2018 08:11:56 PM", "total_users": 0, "total_subreddits": 0, "updated_users": 0, "updated_subreddits": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1317, "message": "Save_file successfully loaded into gui", "asctime": "02/24/2018 08:11:56 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "save_pickled_state", "lineno": 126, "message": "Objects successfully saved", "asctime": "02/24/2018 08:11:59 PM", "total_users_saved": 0, "total_subreddits_saved": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 83, "message": "Object lists loaded from save file", "asctime": "02/24/2018 08:13:43 PM", "total_users": 0, "total_subreddits": 0, "updated_users": 0, "updated_subreddits": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1317, "message": "Save_file successfully loaded into gui", "asctime": "02/24/2018 08:13:43 PM"}
{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename": "main.py", "module": "main", "funcName": "log_unhandled_exception", "lineno": 86, "message": "Unhandled exception", "asctime": "02/24/2018 08:13:45 PM", "exc_info": "Traceback (most recent call last):\n  File \"DownloaderForReddit\\GUI\\DownloaderForRedditGUI.py\", line 741, in remove_user\nAttributeError: 'NoneType' object has no attribute 'row'"}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 83, "message": "Object lists loaded from save file", "asctime": "02/24/2018 08:13:48 PM", "total_users": 0, "total_subreddits": 0, "updated_users": 0, "updated_subreddits": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1317, "message": "Save_file successfully loaded into gui", "asctime": "02/24/2018 08:13:48 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "change_user_list", "lineno": 621, "message": "User list changed to: ALL", "asctime": "02/24/2018 08:13:50 PM"}
{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename": "main.py", "module": "main", "funcName": "log_unhandled_exception", "lineno": 86, "message": "Unhandled exception", "asctime": "02/24/2018 08:13:54 PM", "exc_info": "Traceback (most recent call last):\n  File \"DownloaderForReddit\\GUI\\DownloaderForRedditGUI.py\", line 741, in remove_user\nAttributeError: 'NoneType' object has no attribute 'row'"}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 83, "message": "Object lists loaded from save file", "asctime": "02/24/2018 08:13:56 PM", "total_users": 0, "total_subreddits": 0, "updated_users": 0, "updated_subreddits": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1317, "message": "Save_file successfully loaded into gui", "asctime": "02/24/2018 08:13:56 PM"}
{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename": "main.py", "module": "main", "funcName": "log_unhandled_exception", "lineno": 86, "message": "Unhandled exception", "asctime": "02/24/2018 08:14:05 PM", "exc_info": "Traceback (most recent call last):\n  File \"DownloaderForReddit\\GUI\\DownloaderForRedditGUI.py\", line 1364, in import_save_file\n  File \"DownloaderForReddit\\GUI\\DownloaderForRedditGUI.py\", line 1395, in move_save_files\nPermissionError: [WinError 5] Access is denied: 'C:/save_file.dat' -> 'C:\\\\Users\\\\EC\\\\AppData\\\\Roaming\\\\SomeGuySoftware\\\\DownloaderForReddit\\\\save_file.dat'"}
{"levelname": "ERROR", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 93, "message": "Failed to load from save file", "asctime": "02/24/2018 08:14:08 PM", "exc_info": "Traceback (most recent call last):\n  File \"shelve.py\", line 111, in __getitem__\nKeyError: 'user_list_models'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"DownloaderForReddit\\Persistence\\ObjectStateHandler.py\", line 62, in load_pickled_state\n  File \"shelve.py\", line 114, in __getitem__\nEOFError: Ran out of input", "save_file_location": "C:\\Users\\EC\\AppData\\Roaming\\SomeGuySoftware\\DownloaderForReddit\\save_file"}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "save_pickled_state", "lineno": 126, "message": "Objects successfully saved", "asctime": "02/24/2018 08:14:21 PM", "total_users_saved": 0, "total_subreddits_saved": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 83, "message": "Object lists loaded from save file", "asctime": "02/25/2018 08:16:18 AM", "total_users": 0, "total_subreddits": 0, "updated_users": 0, "updated_subreddits": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1317, "message": "Save_file successfully loaded into gui", "asctime": "02/25/2018 08:16:18 AM"}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "save_pickled_state", "lineno": 126, "message": "Objects successfully saved", "asctime": "02/25/2018 08:16:20 AM", "total_users_saved": 0, "total_subreddits_saved": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 83, "message": "Object lists loaded from save file", "asctime": "02/25/2018 08:35:15 AM", "total_users": 0, "total_subreddits": 0, "updated_users": 0, "updated_subreddits": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1317, "message": "Save_file successfully loaded into gui", "asctime": "02/25/2018 08:35:15 AM"}
{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename": "main.py", "module": "main", "funcName": "log_unhandled_exception", "lineno": 86, "message": "Unhandled exception", "asctime": "02/25/2018 08:35:31 AM", "exc_info": "Traceback (most recent call last):\n  File \"DownloaderForReddit\\GUI\\DownloaderForRedditGUI.py\", line 1364, in import_save_file\n  File \"DownloaderForReddit\\GUI\\DownloaderForRedditGUI.py\", line 1395, in move_save_files\nOSError: [WinError 17] The system cannot move the file to a different disk drive: 'E:/EC/PORTABLE/zbackup\\\\save_file.dat' -> 'C:\\\\Users\\\\EC\\\\AppData\\\\Roaming\\\\SomeGuySoftware\\\\DownloaderForReddit\\\\save_file.dat'"}
{"levelname": "ERROR", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 93, "message": "Failed to load from save file", "asctime": "02/25/2018 08:35:39 AM", "exc_info": "Traceback (most recent call last):\n  File \"shelve.py\", line 111, in __getitem__\nKeyError: 'user_list_models'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"DownloaderForReddit\\Persistence\\ObjectStateHandler.py\", line 62, in load_pickled_state\n  File \"shelve.py\", line 114, in __getitem__\nEOFError: Ran out of input", "save_file_location": "C:\\Users\\EC\\AppData\\Roaming\\SomeGuySoftware\\DownloaderForReddit\\save_file"}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "save_pickled_state", "lineno": 126, "message": "Objects successfully saved", "asctime": "02/25/2018 08:35:43 AM", "total_users_saved": 0, "total_subreddits_saved": 0}

**Comment by EC-O-DE** [comment]
I was going back and forth with versions 2.0->latest trying to get it work....

As I use the app as portable - it would be nice extra feature to keep save_file either with the app (folder) or location of choice. hmmm - but looking at the log there might be some solutions to try. thank u for your efforts on making this app.

**Comment by MalloyDelacroix** [comment]
The problem seems to be that you are trying to import the save file from an external drive.  I did not account for trying to do that.  This will be fixed in the next patch release.  

You are also seeing some permission errors.  Windows will not let you move files from certain folders.  In the future I hope to improve on this functionality.  This is the same problem that was causing the app to crash on startup when it could not create the save file.  This is also what keeps the app from being able to store the save file in the app folder.  The permission errors that the app encounters are something that I hope to have solved by the next major release.

As a solution to the problem right now, if you will open the apps data folder (this can be done through the file menu by clicking "open save location") you can manually copy the file(s) from the external drive into the folder and then restart the app.

**Comment by EC-O-DE** [comment]
I cleared inheritances and file/folder permissions ~ but it nags that it can't write to the location.

So solution:
NTFS junction from appdata to a folder on the same drive with exe (not the exe folder though, a config location easy to back up)

Works! But it doesn't "read contents" of the save file thus does not populate user and subreddit lists - but remembers other details... So: CMD+A: dir /b > foldernamesaslist.txt

:)

**Comment by EC-O-DE** [comment]
Any updates?
