### ISSUE TITLE
Folders for Users vs Subreddits

### ISSUE THREAD

**Issue by DankMemeGuy** [MalloyDelacroix/DownloaderForReddit#98]
How do I set the the main folder for all users to be saved in, and one for subreddits?

Right now both download in one folder.

**Comment by MalloyDelacroix** [comment]
Right now the only option is for them to all save to the same master folder.  

You can set custom save paths on individual users/subreddits through the user/subreddit settings dialog.  But it won't do all users or all subreddits at once.

**Comment by DankMemeGuy** [comment]
In that case may I suggest this as a feature request?

**Comment by DankMemeGuy** [comment]
If this isn't possible due to complexity, would it be possible to multi-select users/subeditts to change the location?

**Comment by MalloyDelacroix** [comment]
Both of these features are actually already incorporated into the version 3 development branch.  I am working to get the new version released as soon as possible.  I am hoping there should be at least a beta version ready to go in the next month.

**Comment by DankMemeGuy** [comment]
Oh you're the best. Thank you!
